
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from a WSDL file, the file may contain up to three 
// sets of C/C++ definitions. The first set consists of function declarations that can be 
// used in calling operations on a running web service from client applications. 
// The second set consists of callback declarations that can be used in the 
// implementation of web services.  
// The third set contains definitions C/C++ structures that are used for serialization of 
// C/C++ types to schema types defined in the WSDL file.
//
// The set of function declarations for web services clients may contain the 
// following declaration: 
//
//    HRESULT WINAPI DefaultBinding_ICalculator_Add(
//       __in WS_SERVICE_PROXY* _serviceProxy,
//       __in int a, 
//       __in int b, 
//       __out int* result, 
//       __in WS_HEAP* _heap,
//       __in_opt WS_CALL_PROPERTY* _callProperties,
//       __in const ULONG _callPropertyCount,
//       __in_opt const WS_ASYNC_CONTEXT*_asyncContext,
//       __in_opt WS_ERROR* _error);
//
// This function can be called from an application code to request ICalculator web 
// service to perform operation Add using two integers a and b as input data.
// Once the web service processes this request and sends the result back,
// the result is returned to the caller of this function in the "result" parameter.
// A WS_SERVICE_PROXY must be created using WsCreateServiceProxy() function
// before this proxy function can be invoked.
//
// The set of callbacks for implementation of web services may contain the following 
// definition of a callback: 
//
//    typedef HRESULT (CALLBACK* DefaultBinding_ICalculator_AddCallback) (
//       __in const WS_OPERATION_CONTEXT* _context,
//       __in int a, 
//       __in int b, 
//       __out int* result, 
//       __in const WS_ASYNC_CONTEXT* _asyncContext,
//       __in WS_ERROR* _error); 
//
//    typedef struct DefaultBinding_ICalculatorFunctionTable 
//    {
//         DefaultBinding_ICalculator_AddCallback DefaultBinding_ICalculator_Add;
//    } DefaultBinding_ICalculatorFunctionTable;
//
// This definition can be used to implement a function that defines the Add operation 
// as a part of an ICalculator web service. Once this callback is implemented and 
// the web service is deployed and running, if a client applications attempts to 
// execute the operation Add, the implementation of this callback is called and 
// it receives two integers a and b as input data and it returns a third integer 
// that is the result of the operation. A WS_SERVICE_ENDPOINT must be filled out, 
// and its contract field set to instance of such a function table.  
// WsCreateServiceHost may then be used to register the endpoint as a service.
// 
// The set with definitions of C/C++ structures may contain a definition of the following 
// structure:
//    typedef struct ContactInfo 
//    {
//			WCHAR*  name;
//			WCHAR*  email;
//			__int64 contactID;
//	  } ContactInfo;
//
// This structure corresponds to the following complex type defined in the WSDL file:
//    <s:complexType name="ContactInfo">
//      <s:sequence>
//        <s:element minOccurs="1" maxOccurs="1" name="name" type="s:string" />
//        <s:element minOccurs="1" maxOccurs="1" name="email" type="s:string" />
//        <s:element minOccurs="1" maxOccurs="1" name="contactID" type="s:long" />
//      </s:sequence>
//    </s:complexType>
//
// For more information about content of this file, please see the documentation for
// Wsutil compiler.
// If Wsutil generates this file from a WSDL file and policy processing is enabled using
// policy switch, the file may contain declaration of functions that can be used 
// for creating a proxy to a web service or an endpoint of a web service. 
// For example, the file may contain declaration of the following function:
//
//    HRESULT DefaultBinding_ICalculator_CreateServiceProxy(
//    __in WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
//    __in_ecount_opt(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
//    __in const ULONG proxyPropertyCount,
//    __deref_out_opt WS_SERVICE_PROXY** proxy,
//    __in_opt WS_ERROR* error);
//
// This function can be called from application code to create a service
// proxy object. A service proxy must be created before any request can be sent 
// to the web service.
//
// Also, the file may contain declaration of the following function :
//
//    HRESULT DefaultBinding_ICalculator_CreateServiceEndpoint(
//    __in WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
//    __in_opt WS_STRING address,
//    __in_opt struct DefaultBinding_ICalculatorFunctionTable* functionTable,
//    __in_opt WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
//    __in_ecount_opt(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
//    __in const ULONG endpointPropertyCount,
//    __in WS_HEAP* heap,
//    __deref_out_opt WS_SERVICE_ENDPOINT** serviceEndpoint,
//    __in_opt WS_ERROR* error);
//
// This function can be used to create a Service Host object, which has to be 
// created before a web services starts receiving requests from its clients.
//
// For more information about content of this file, please see the documentation for
// Wsutil compiler.
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following client functions were generated:

//     WSHttpBinding_IEnterpriseService_Process

// The following server function tables were generated:

//     struct WSHttpBinding_IEnterpriseServiceFunctionTable

// the following policy helpers were generated:

//  WSHttpBinding_IEnterpriseService_CreateServiceProxy;
//  WSHttpBinding_IEnterpriseService_CreateServiceEndpoint;

// The following header files must be included in this order before this one

// #include <WebServices.h>
// #include "tempuri.org.xsd.h"

////////////////////////////////////////////////
// Policy helper routines
////////////////////////////////////////////////

//  WS_CHANNEL_PROPERTY_ENCODING = WS_ENCODING_XML_UTF8,
//  WS_CHANNEL_PROPERTY_ADDRESSING_VERSION = WS_ADDRESSING_VERSION_1_0,
//  WS_ENVELOPE_VERSION = WS_ENVELOPE_VERSION_SOAP_1_2,
//  WS_PROTECTION_LEVEL = WS_PROTECTION_LEVEL_SIGN_AND_ENCRYPT,
//  WS_SECURITY_TIMESTAMP_USAGE = WS_SECURITY_TIMESTAMP_USAGE_ALWAYS,
//  WS_SECURITY_HEADER_VERSION = WS_SECURITY_HEADER_VERSION_1_1,
//  WS_SECURITY_HEADER_LAYOUT = WS_SECURITY_HEADER_LAYOUT_STRICT,
//  WS_SECURITY_ALGORITHM_SUITE_NAME = WS_SECURITY_ALGORITHM_SUITE_NAME_BASIC256,
//  WS_SSL_TRANSPORT_SECURITY_BINDING_POLICY_DESCRIPTION
//  WS_USERNAME_MESSAGE_SECURITY_BINDING_POLICY_DESCRIPTION
// client channel type: WS_CHANNEL_TYPE_REQUEST, service endpoint channel type: WS_CHANNEL_TYPE_REPLY

HRESULT WSHttpBinding_IEnterpriseService_CreateServiceProxy(
    __in_opt WS_HTTP_SSL_USERNAME_BINDING_TEMPLATE* templateValue,
    __in_ecount_opt(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    __in const ULONG proxyPropertyCount,
    __deref_out_opt WS_SERVICE_PROXY** _serviceProxy,
    __in_opt WS_ERROR* error);

struct WSHttpBinding_IEnterpriseServiceFunctionTable;
HRESULT WSHttpBinding_IEnterpriseService_CreateServiceEndpoint(
    __in_opt WS_HTTP_SSL_USERNAME_BINDING_TEMPLATE* templateValue,
    __in_opt CONST WS_STRING* address,
    __in_opt struct WSHttpBinding_IEnterpriseServiceFunctionTable* functionTable,
    __in_opt WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    __in_ecount_opt(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    __in const ULONG endpointPropertyCount,
    __in WS_HEAP* heap,
    __deref_out_opt WS_SERVICE_ENDPOINT** serviceEndpoint,
    __in_opt WS_ERROR* error);

////////////////////////////////////////////////
// Client functions definitions
////////////////////////////////////////////////

// operation: WSHttpBinding_IEnterpriseService_Process
HRESULT WINAPI WSHttpBinding_IEnterpriseService_Process(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in_opt __nullterminated WCHAR* message, 
    __out_opt __deref __nullterminated WCHAR** ProcessResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error);

////////////////////////////////////////////////
// Service functions definitions
////////////////////////////////////////////////

typedef HRESULT (CALLBACK* WSHttpBinding_IEnterpriseService_ProcessCallback) (
    __in const WS_OPERATION_CONTEXT* _context,
    __in_opt __nullterminated WCHAR* message, 
    __out_opt __deref __nullterminated WCHAR** ProcessResult, 
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error);

// binding: WSHttpBinding_IEnterpriseService
typedef struct WSHttpBinding_IEnterpriseServiceFunctionTable 
{
    WSHttpBinding_IEnterpriseService_ProcessCallback WSHttpBinding_IEnterpriseService_Process;
} WSHttpBinding_IEnterpriseServiceFunctionTable;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _tempuri_org_wsdl
{
    struct // messages
    {
        // message: IEnterpriseService_Process_InputMessage
        // c type: _Process
        // action: "http://tempuri.org/IEnterpriseService/Process"
        // messageDescription: tempuri_org_wsdl.messages.IEnterpriseService_Process_InputMessage
        WS_MESSAGE_DESCRIPTION IEnterpriseService_Process_InputMessage;
        
        // message: IEnterpriseService_Process_OutputMessage
        // c type: _ProcessResponse
        // action: "http://tempuri.org/IEnterpriseService/ProcessResponse"
        // messageDescription: tempuri_org_wsdl.messages.IEnterpriseService_Process_OutputMessage
        WS_MESSAGE_DESCRIPTION IEnterpriseService_Process_OutputMessage;
        
    } messages;
    struct // contracts
    {
        // binding: WSHttpBinding_IEnterpriseService
        // portType: IEnterpriseService
        // operation: WSHttpBinding_IEnterpriseService_Process
        //     input message: IEnterpriseService_Process_InputMessage
        //     output message: IEnterpriseService_Process_OutputMessage
        // contractDescription: tempuri_org_wsdl.contracts.WSHttpBinding_IEnterpriseService
        WS_CONTRACT_DESCRIPTION WSHttpBinding_IEnterpriseService;
        
    } contracts;
    struct // policies
    {
        // policy for binding: WSHttpBinding_IEnterpriseService
        // port name: WSHttpBinding_IEnterpriseService, binding: WSHttpBinding_IEnterpriseService, namespace: http://tempuri.org/
        WS_HTTP_SSL_USERNAME_POLICY_DESCRIPTION WSHttpBinding_IEnterpriseService;
    } policies;
    struct
    { // endpointReferences
        struct
        {  // WSHttpBinding_IEnterpriseService
            WS_ENDPOINT_ADDRESS_DESCRIPTION endpointAddressDescription;
            WS_XML_STRING* endpointReferenceString;
        } WSHttpBinding_IEnterpriseService;  // endof WSHttpBinding_IEnterpriseService
    } endpointReferences;  // endof endpointReferences 
} _tempuri_org_wsdl;

extern const _tempuri_org_wsdl tempuri_org_wsdl;

#ifdef __cplusplus
}
#endif

