
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "tempuri.org.xsd.h"
#include "tempuri.org.wsdl.h"

typedef struct _tempuri_org_wsdlLocalDefinitions 
{
    struct // messages
    {
        WS_MESSAGE_DESCRIPTION IEnterpriseService_Process_InputMessage;
        WS_MESSAGE_DESCRIPTION IEnterpriseService_Process_OutputMessage;
    } messages; // end of messages
    struct // contracts
    {
        struct // WSHttpBinding_IEnterpriseService
        {
            struct // WSHttpBinding_IEnterpriseService_Process
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION WSHttpBinding_IEnterpriseService_Process;
            } WSHttpBinding_IEnterpriseService_Process;
            WS_OPERATION_DESCRIPTION* operations[1];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } WSHttpBinding_IEnterpriseService;
    } contracts;  // endof contracts 
    struct // policies
    {
        struct // WSHttpBinding_IEnterpriseService
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
            WS_PROTECTION_LEVEL protectionLevel;
            WS_SECURITY_TIMESTAMP_USAGE timestampUsage;
            WS_SECURITY_HEADER_VERSION headerVersion;
            WS_SECURITY_HEADER_LAYOUT  headerLayout;
            WS_SECURITY_ALGORITHM_SUITE_NAME  securityAlgorithmSuite;
            WS_SECURITY_PROPERTY securityPropertiesArray[5];
        } WSHttpBinding_IEnterpriseService;
    } policies;
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING IEnterpriseService_Process_InputMessageactionName;  // http://tempuri.org/IEnterpriseService/Process
            WS_XML_STRING IEnterpriseService_Process_OutputMessageactionName;  // http://tempuri.org/IEnterpriseService/ProcessResponse
            WS_XML_STRING WSHttpBinding_IEnterpriseServiceendpointReferenceString;  // <wsa10:EndpointReference xmlns:wsa10="http://www.w3.org/2005/08/addressing">...
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _tempuri_org_wsdlLocalDefinitions;


typedef struct WSHttpBinding_IEnterpriseService_ProcessParamStruct 
{
    WCHAR** message;
    WCHAR** ProcessResult;
} WSHttpBinding_IEnterpriseService_ProcessParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK WSHttpBinding_IEnterpriseService_ProcessOperationStub(
    __in const WS_OPERATION_CONTEXT* _context,
    __in void* _stackStruct,
    __in const void* _callback,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    WSHttpBinding_IEnterpriseService_ProcessCallback _operation = (WSHttpBinding_IEnterpriseService_ProcessCallback)_callback;
    WSHttpBinding_IEnterpriseService_ProcessParamStruct *_stack =(WSHttpBinding_IEnterpriseService_ProcessParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->message),
        (_stack->ProcessResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _tempuri_org_wsdlLocalDefinitions tempuri_org_wsdlLocalDefinitions =
{
    { // messages
        {    // message description for IEnterpriseService_Process_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IEnterpriseService_Process_InputMessageactionName, // http://tempuri.org/IEnterpriseService/Process
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.Process, 
        },    // message description for IEnterpriseService_Process_InputMessage
        {    // message description for IEnterpriseService_Process_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IEnterpriseService_Process_OutputMessageactionName, // http://tempuri.org/IEnterpriseService/ProcessResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.ProcessResponse, 
        },    // message description for IEnterpriseService_Process_OutputMessage
    }, // end of messages 
    { // contracts
        {    // WSHttpBinding_IEnterpriseService,
            { // WSHttpBinding_IEnterpriseService_Process
                { // parameter descriptions for WSHttpBinding_IEnterpriseService_Process
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1 },
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0 },
                },    // parameter descriptions for WSHttpBinding_IEnterpriseService_Process
                {    // operation description for WSHttpBinding_IEnterpriseService_Process
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IEnterpriseService_Process_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IEnterpriseService_Process_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.WSHttpBinding_IEnterpriseService.WSHttpBinding_IEnterpriseService_Process.params,
                    WSHttpBinding_IEnterpriseService_ProcessOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for WSHttpBinding_IEnterpriseService_Process
            },  // WSHttpBinding_IEnterpriseService_Process
            {    // array of operations for WSHttpBinding_IEnterpriseService
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.WSHttpBinding_IEnterpriseService.WSHttpBinding_IEnterpriseService_Process.WSHttpBinding_IEnterpriseService_Process,
            },    // array of operations for WSHttpBinding_IEnterpriseService
            {    // contract description for WSHttpBinding_IEnterpriseService
            1,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.WSHttpBinding_IEnterpriseService.operations,
            },  // end of contract description for WSHttpBinding_IEnterpriseService
        },    // WSHttpBinding_IEnterpriseService
    }, //  end of contracts 
    {// policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_1_0,
            WS_ENVELOPE_VERSION_SOAP_1_2,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.encoding,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.addressingVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.envelopeVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.envelopeVersion),
                },
            },
            WS_PROTECTION_LEVEL_SIGN_AND_ENCRYPT,
            WS_SECURITY_TIMESTAMP_USAGE_ALWAYS,
            WS_SECURITY_HEADER_VERSION_1_1,
            WS_SECURITY_HEADER_LAYOUT_STRICT,
            WS_SECURITY_ALGORITHM_SUITE_NAME_BASIC256,
            { // securityPropertiesArray
                {
                    WS_SECURITY_PROPERTY_TRANSPORT_PROTECTION_LEVEL,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.protectionLevel,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.protectionLevel),
                },
                {
                    WS_SECURITY_PROPERTY_TIMESTAMP_USAGE,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.timestampUsage,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.timestampUsage),
                },
                {
                    WS_SECURITY_PROPERTY_SECURITY_HEADER_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.headerVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.headerVersion),
                },
                {
                    WS_SECURITY_PROPERTY_SECURITY_HEADER_LAYOUT,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.headerLayout,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.headerLayout),
                },
                {
                    WS_SECURITY_PROPERTY_ALGORITHM_SUITE_NAME,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.securityAlgorithmSuite,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.securityAlgorithmSuite),
                },
            },
        },   // end of WSHttpBinding_IEnterpriseService,
    }, // policies
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IEnterpriseService/Process",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IEnterpriseService/ProcessResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("<wsa10:EndpointReference xmlns:wsa10=\"http://www.w3.org/2005/08/addressing\">\n        <wsa10:Address>https://localhost:8000/EnterpriseService/</wsa10:Address>\n        <Identity xmlns=\"http://schemas.xmlsoap.org/ws/2006/02/addressingidentity\">\n          <Dns>localhost</Dns>\n        </Identity>\n      </wsa10:EndpointReference>",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 2),
        },  // end of xmlStrings
        
        {   // tempuri_org_wsdldictionary
        // 10058828-9da3-4840-b066-11a78d477967 
        { 0x10058828, 0x9da3, 0x4840, { 0xb0, 0x66, 0x11,0xa7, 0x8d, 0x47, 0x79, 0x67 } },
        (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings,
        3,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of tempuri_org_wsdlLocalDefinitions


// operation: WSHttpBinding_IEnterpriseService_Process
HRESULT WINAPI WSHttpBinding_IEnterpriseService_Process(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in_opt __nullterminated WCHAR* message, 
    __out_opt __deref __nullterminated WCHAR** ProcessResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &message;
    _argList[1] = &ProcessResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.WSHttpBinding_IEnterpriseService.WSHttpBinding_IEnterpriseService_Process.WSHttpBinding_IEnterpriseService_Process,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
const _tempuri_org_wsdl tempuri_org_wsdl =
{
    {// messages
        {    // message description for IEnterpriseService_Process_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IEnterpriseService_Process_InputMessageactionName, // http://tempuri.org/IEnterpriseService/Process
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.Process, 
        },    // message description for IEnterpriseService_Process_InputMessage
        {    // message description for IEnterpriseService_Process_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IEnterpriseService_Process_OutputMessageactionName, // http://tempuri.org/IEnterpriseService/ProcessResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.ProcessResponse, 
        },    // message description for IEnterpriseService_Process_OutputMessage
    }, // messages
    {// contracts
        {   // WSHttpBinding_IEnterpriseService
            1,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.WSHttpBinding_IEnterpriseService.operations,
        },    // end of WSHttpBinding_IEnterpriseService
    }, // contracts
    { // policies
        {  // template description for WSHttpBinding_IEnterpriseService
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.channelPropertiesArray,
                3,
            },
            {  // security properties
                (WS_SECURITY_PROPERTY*)&tempuri_org_wsdlLocalDefinitions.policies.WSHttpBinding_IEnterpriseService.securityPropertiesArray,
                5,
            },
            { // sslBinding
                { 
                    0,
                },
            },
            { // userNameBinding
                { 
                    0,
                },
                WS_SUPPORTING_MESSAGE_SECURITY_USAGE
            },
        },  // end of template description
    },  // policies
    { // endpointReferences
        { // WSHttpBinding_IEnterpriseService
            { // endpointAddressDescription
                WS_ADDRESSING_VERSION_1_0,
            },
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.WSHttpBinding_IEnterpriseServiceendpointReferenceString, // <wsa10:EndpointReference xmlns:wsa10="http://www.w3.org/2005/08/addressing">...
        },  // endof WSHttpBinding_IEnterpriseService
    },  // endof endpointReferences 
}; // end of _tempuri_org_wsdl

HRESULT WSHttpBinding_IEnterpriseService_CreateServiceProxy(
    __in_opt WS_HTTP_SSL_USERNAME_BINDING_TEMPLATE* templateValue,
    __in_ecount_opt(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    __in const ULONG proxyPropertyCount,
    __deref_out_opt WS_SERVICE_PROXY** _serviceProxy,
    __in_opt WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_SSL_USERNAME_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_SSL_USERNAME_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.WSHttpBinding_IEnterpriseService,
        sizeof(tempuri_org_wsdl.policies.WSHttpBinding_IEnterpriseService),
        _serviceProxy,
        error);
}

HRESULT WSHttpBinding_IEnterpriseService_CreateServiceEndpoint(
    __in_opt WS_HTTP_SSL_USERNAME_BINDING_TEMPLATE* templateValue,
    __in_opt CONST WS_STRING* address,
    __in_opt struct WSHttpBinding_IEnterpriseServiceFunctionTable* functionTable,
    __in_opt WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    __in_ecount_opt(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    __in const ULONG endpointPropertyCount,
    __in WS_HEAP* heap,
    __deref_out_opt WS_SERVICE_ENDPOINT** serviceEndpoint,
    __in_opt WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &tempuri_org_wsdl.contracts.WSHttpBinding_IEnterpriseService;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_SSL_USERNAME_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_SSL_USERNAME_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.WSHttpBinding_IEnterpriseService,
        sizeof(tempuri_org_wsdl.policies.WSHttpBinding_IEnterpriseService),
        serviceEndpoint,
        error);
}
