
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct // _Process
        {
            WS_FIELD_DESCRIPTION message;
            WS_FIELD_DESCRIPTION* _ProcessFields [1]; 
        } _Processdescs; // end of _Process
        struct // _ProcessResponse
        {
            WS_FIELD_DESCRIPTION ProcessResult;
            WS_FIELD_DESCRIPTION* _ProcessResponseFields [1]; 
        } _ProcessResponsedescs; // end of _ProcessResponse
    } globalElements;  // end of global elements
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING _ProcessTypeName;  // Process
            WS_XML_STRING _ProcessTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _ProcessmessageLocalName;  // message
            WS_XML_STRING _ProcessResponseTypeName;  // ProcessResponse
            WS_XML_STRING _ProcessResponseProcessResultLocalName;  // ProcessResult
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {   // _Process
            { // field description for message
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessmessageLocalName, // message
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_Process, message),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for message
            {    // fields description for _Process
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Processdescs.message,
            },
        },    // _Process
        {   // _ProcessResponse
            { // field description for ProcessResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessResponseProcessResultLocalName, // ProcessResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_ProcessResponse, ProcessResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for ProcessResult
            {    // fields description for _ProcessResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._ProcessResponsedescs.ProcessResult,
            },
        },    // _ProcessResponse
    }, // end of global elements
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("Process",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("message",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("ProcessResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("ProcessResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
        },  // end of xmlStrings
        
        {   // tempuri_org_xsddictionary
        // 84be0207-c3d7-48a1-8541-654a94e17dfd 
        { 0x84be0207, 0xc3d7, 0x48a1, { 0x85, 0x41, 0x65,0x4a, 0x94, 0xe1, 0x7d, 0xfd } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        5,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {// globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessTypeName, // Process
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.Process,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessResponseTypeName, // ProcessResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.ProcessResponse,
        },
    }, // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_Process),
        __alignof(_Process),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._Processdescs._ProcessFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._Processdescs._ProcessFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessTypeName, // Process
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _Process
        {
        sizeof(_ProcessResponse),
        __alignof(_ProcessResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._ProcessResponsedescs._ProcessResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._ProcessResponsedescs._ProcessResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessResponseTypeName, // ProcessResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._ProcessTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _ProcessResponse
    }, // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
