//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DicomRIAService.Web.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatasetsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatasetsEntities object using the connection string found in the 'DatasetsEntities' section of the application configuration file.
        /// </summary>
        public DatasetsEntities() : base("name=DatasetsEntities", "DatasetsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatasetsEntities object.
        /// </summary>
        public DatasetsEntities(string connectionString) : base(connectionString, "DatasetsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatasetsEntities object.
        /// </summary>
        public DatasetsEntities(EntityConnection connection) : base(connection, "DatasetsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dataset> Datasets
        {
            get
            {
                if ((_Datasets == null))
                {
                    _Datasets = base.CreateObjectSet<Dataset>("Datasets");
                }
                return _Datasets;
            }
        }
        private ObjectSet<Dataset> _Datasets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Progress> Progresses
        {
            get
            {
                if ((_Progresses == null))
                {
                    _Progresses = base.CreateObjectSet<Progress>("Progresses");
                }
                return _Progresses;
            }
        }
        private ObjectSet<Progress> _Progresses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Image> Images
        {
            get
            {
                if ((_Images == null))
                {
                    _Images = base.CreateObjectSet<Image>("Images");
                }
                return _Images;
            }
        }
        private ObjectSet<Image> _Images;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Datasets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDatasets(Dataset dataset)
        {
            base.AddObject("Datasets", dataset);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Progresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProgresses(Progress progress)
        {
            base.AddObject("Progresses", progress);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Images EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImages(Image image)
        {
            base.AddObject("Images", image);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatasetsModel", Name="Dataset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dataset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dataset object.
        /// </summary>
        /// <param name="uid">Initial value of the uid property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="mod">Initial value of the mod property.</param>
        /// <param name="man">Initial value of the man property.</param>
        /// <param name="model">Initial value of the model property.</param>
        /// <param name="ort">Initial value of the ort property.</param>
        /// <param name="qa">Initial value of the qa property.</param>
        /// <param name="cpd">Initial value of the cpd property.</param>
        /// <param name="desc">Initial value of the desc property.</param>
        /// <param name="icnt">Initial value of the icnt property.</param>
        /// <param name="app">Initial value of the app property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="pln">Initial value of the pln property.</param>
        public static Dataset CreateDataset(global::System.String uid, global::System.String name, global::System.String mod, global::System.String man, global::System.String model, global::System.String ort, global::System.Boolean qa, global::System.Boolean cpd, global::System.String desc, global::System.Int32 icnt, global::System.String app, global::System.String type, global::System.String pln)
        {
            Dataset dataset = new Dataset();
            dataset.uid = uid;
            dataset.name = name;
            dataset.mod = mod;
            dataset.man = man;
            dataset.model = model;
            dataset.ort = ort;
            dataset.qa = qa;
            dataset.cpd = cpd;
            dataset.desc = desc;
            dataset.icnt = icnt;
            dataset.app = app;
            dataset.type = type;
            dataset.pln = pln;
            return dataset;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uid
        {
            get
            {
                return _uid;
            }
            set
            {
                if (_uid != value)
                {
                    OnuidChanging(value);
                    ReportPropertyChanging("uid");
                    _uid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("uid");
                    OnuidChanged();
                }
            }
        }
        private global::System.String _uid;
        partial void OnuidChanging(global::System.String value);
        partial void OnuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mod
        {
            get
            {
                return _mod;
            }
            set
            {
                OnmodChanging(value);
                ReportPropertyChanging("mod");
                _mod = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mod");
                OnmodChanged();
            }
        }
        private global::System.String _mod;
        partial void OnmodChanging(global::System.String value);
        partial void OnmodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String man
        {
            get
            {
                return _man;
            }
            set
            {
                OnmanChanging(value);
                ReportPropertyChanging("man");
                _man = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("man");
                OnmanChanged();
            }
        }
        private global::System.String _man;
        partial void OnmanChanging(global::System.String value);
        partial void OnmanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private global::System.String _model;
        partial void OnmodelChanging(global::System.String value);
        partial void OnmodelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ort
        {
            get
            {
                return _ort;
            }
            set
            {
                OnortChanging(value);
                ReportPropertyChanging("ort");
                _ort = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ort");
                OnortChanged();
            }
        }
        private global::System.String _ort;
        partial void OnortChanging(global::System.String value);
        partial void OnortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean qa
        {
            get
            {
                return _qa;
            }
            set
            {
                OnqaChanging(value);
                ReportPropertyChanging("qa");
                _qa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qa");
                OnqaChanged();
            }
        }
        private global::System.Boolean _qa;
        partial void OnqaChanging(global::System.Boolean value);
        partial void OnqaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean cpd
        {
            get
            {
                return _cpd;
            }
            set
            {
                OncpdChanging(value);
                ReportPropertyChanging("cpd");
                _cpd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cpd");
                OncpdChanged();
            }
        }
        private global::System.Boolean _cpd;
        partial void OncpdChanging(global::System.Boolean value);
        partial void OncpdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String desc
        {
            get
            {
                return _desc;
            }
            set
            {
                OndescChanging(value);
                ReportPropertyChanging("desc");
                _desc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("desc");
                OndescChanged();
            }
        }
        private global::System.String _desc;
        partial void OndescChanging(global::System.String value);
        partial void OndescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 icnt
        {
            get
            {
                return _icnt;
            }
            set
            {
                OnicntChanging(value);
                ReportPropertyChanging("icnt");
                _icnt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("icnt");
                OnicntChanged();
            }
        }
        private global::System.Int32 _icnt;
        partial void OnicntChanging(global::System.Int32 value);
        partial void OnicntChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String app
        {
            get
            {
                return _app;
            }
            set
            {
                OnappChanging(value);
                ReportPropertyChanging("app");
                _app = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("app");
                OnappChanged();
            }
        }
        private global::System.String _app;
        partial void OnappChanging(global::System.String value);
        partial void OnappChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pln
        {
            get
            {
                return _pln;
            }
            set
            {
                OnplnChanging(value);
                ReportPropertyChanging("pln");
                _pln = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pln");
                OnplnChanged();
            }
        }
        private global::System.String _pln;
        partial void OnplnChanging(global::System.String value);
        partial void OnplnChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatasetsModel", Name="Image")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Image : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Image object.
        /// </summary>
        /// <param name="suid">Initial value of the suid property.</param>
        /// <param name="uid">Initial value of the uid property.</param>
        /// <param name="file">Initial value of the file property.</param>
        public static Image CreateImage(global::System.String suid, global::System.String uid, global::System.String file)
        {
            Image image = new Image();
            image.suid = suid;
            image.uid = uid;
            image.file = file;
            return image;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String suid
        {
            get
            {
                return _suid;
            }
            set
            {
                if (_suid != value)
                {
                    OnsuidChanging(value);
                    ReportPropertyChanging("suid");
                    _suid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("suid");
                    OnsuidChanged();
                }
            }
        }
        private global::System.String _suid;
        partial void OnsuidChanging(global::System.String value);
        partial void OnsuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uid
        {
            get
            {
                return _uid;
            }
            set
            {
                if (_uid != value)
                {
                    OnuidChanging(value);
                    ReportPropertyChanging("uid");
                    _uid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("uid");
                    OnuidChanged();
                }
            }
        }
        private global::System.String _uid;
        partial void OnuidChanging(global::System.String value);
        partial void OnuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String file
        {
            get
            {
                return _file;
            }
            set
            {
                OnfileChanging(value);
                ReportPropertyChanging("file");
                _file = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("file");
                OnfileChanged();
            }
        }
        private global::System.String _file;
        partial void OnfileChanging(global::System.String value);
        partial void OnfileChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatasetsModel", Name="Progress")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Progress : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Progress object.
        /// </summary>
        /// <param name="uid">Initial value of the uid property.</param>
        /// <param name="aetitle">Initial value of the aetitle property.</param>
        /// <param name="port">Initial value of the port property.</param>
        /// <param name="progress1">Initial value of the progress1 property.</param>
        /// <param name="total">Initial value of the total property.</param>
        /// <param name="server">Initial value of the server property.</param>
        /// <param name="message">Initial value of the message property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="date">Initial value of the date property.</param>
        /// <param name="state">Initial value of the state property.</param>
        public static Progress CreateProgress(global::System.String uid, global::System.String aetitle, global::System.Int32 port, global::System.Int32 progress1, global::System.Int32 total, global::System.String server, global::System.String message, global::System.String name, global::System.DateTime date, global::System.String state)
        {
            Progress progress = new Progress();
            progress.uid = uid;
            progress.aetitle = aetitle;
            progress.port = port;
            progress.progress1 = progress1;
            progress.total = total;
            progress.server = server;
            progress.message = message;
            progress.name = name;
            progress.date = date;
            progress.state = state;
            return progress;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uid
        {
            get
            {
                return _uid;
            }
            set
            {
                if (_uid != value)
                {
                    OnuidChanging(value);
                    ReportPropertyChanging("uid");
                    _uid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("uid");
                    OnuidChanged();
                }
            }
        }
        private global::System.String _uid;
        partial void OnuidChanging(global::System.String value);
        partial void OnuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String aetitle
        {
            get
            {
                return _aetitle;
            }
            set
            {
                if (_aetitle != value)
                {
                    OnaetitleChanging(value);
                    ReportPropertyChanging("aetitle");
                    _aetitle = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("aetitle");
                    OnaetitleChanged();
                }
            }
        }
        private global::System.String _aetitle;
        partial void OnaetitleChanging(global::System.String value);
        partial void OnaetitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 port
        {
            get
            {
                return _port;
            }
            set
            {
                if (_port != value)
                {
                    OnportChanging(value);
                    ReportPropertyChanging("port");
                    _port = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("port");
                    OnportChanged();
                }
            }
        }
        private global::System.Int32 _port;
        partial void OnportChanging(global::System.Int32 value);
        partial void OnportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 progress1
        {
            get
            {
                return _progress1;
            }
            set
            {
                Onprogress1Changing(value);
                ReportPropertyChanging("progress1");
                _progress1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("progress1");
                Onprogress1Changed();
            }
        }
        private global::System.Int32 _progress1;
        partial void Onprogress1Changing(global::System.Int32 value);
        partial void Onprogress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 total
        {
            get
            {
                return _total;
            }
            set
            {
                OntotalChanging(value);
                ReportPropertyChanging("total");
                _total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total");
                OntotalChanged();
            }
        }
        private global::System.Int32 _total;
        partial void OntotalChanging(global::System.Int32 value);
        partial void OntotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String server
        {
            get
            {
                return _server;
            }
            set
            {
                if (_server != value)
                {
                    OnserverChanging(value);
                    ReportPropertyChanging("server");
                    _server = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("server");
                    OnserverChanged();
                }
            }
        }
        private global::System.String _server;
        partial void OnserverChanging(global::System.String value);
        partial void OnserverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String message
        {
            get
            {
                return _message;
            }
            set
            {
                OnmessageChanging(value);
                ReportPropertyChanging("message");
                _message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("message");
                OnmessageChanged();
            }
        }
        private global::System.String _message;
        partial void OnmessageChanging(global::System.String value);
        partial void OnmessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                if (_date != value)
                {
                    OndateChanging(value);
                    ReportPropertyChanging("date");
                    _date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("date");
                    OndateChanged();
                }
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();

        #endregion
    
    }

    #endregion
    
}
