// $Id: ICadReportReader.cs,v 1.1.4.1 2009-06-29 13:22:25 kchalupa Exp $
//
// Copyright © 2009, Viatronix Inc., All Rights Reserved.
//
// This is PROPRIETARY SOURCE CODE of Viatronix Inc. The contents of this file
// may not be disclosed to third parties, copied or duplicated in any form,
// in whole or in part, without the prior written permission Viatronix Inc.
//
// Owner: [Kyle R Chalupa] [kchalupa@viatronix.com]

using System;
using System.Xml;
using System.Collections.Generic;
using System.Text;

namespace Viatronix.v3D.Utilities.CadParser
{
  /// <summary>
  /// Establishes an interface for reading Cad reports generated by our VC plugin.
  /// </summary>
  public interface ICadReportReader
  {

    #region properties

    /// <summary>
    /// Gets or sets the list of findings.
    /// </summary>
    List<CadFinding> Findings
    {
      get;
      set;
    } // Findings

    #endregion

    #region methods

    /// <summary>
    /// Indicates whether this ICadReportReader can read the report.
    /// </summary>
    /// <param name="filePath">The report to read.</param>
    /// <returns>True if this ICadReportReader can read the report, false otherwise.</returns>
    bool CanReadReport(string filePath);

    /// <summary>
    /// Reads an XmlNode and creates a CadFinding from it.
    /// </summary>
    /// <param name="node">The finding node to read.</param>
    /// <returns>A CadFinding based on the finding node.</returns>
    CadFinding ReadFindingFromXml(XmlNode node);

    /// <summary>
    /// Reads the Xml file and builds up the list of cad findings.
    /// </summary>
    /// <param name="filePath">The file to read.</param>
    /// <param name="dicomPath">The path to the DICOM series if the reader requires it.</param>
    void ReadXmlFile(string filePath, string dicomPath);

    /// <summary>
    /// Saves the data read in out to a text file.
    /// </summary>
    /// <param name="filePath">The file to write out to.</param>
    /// <param name="inputFilePath">The input file that generated this output.</param>
    void SaveTextFile(string filePath, string inputFilePath);

    #endregion

  } // ICadReportReader
} // namespace Viatronix.v3D.Utilities.CadParser

#region revision history

// $Log: not supported by cvs2svn $
// Revision 1.1  2009/05/19 13:39:34  kchalupa
// Initial Revision
//
// $Header: D:\CVS\cvsRepository/V3D/src/Viatronix.v3D.Tools/MedicSightAET/ICadReportReader.cs,v 1.1.4.1 2009-06-29 13:22:25 kchalupa Exp $
// $Id: ICadReportReader.cs,v 1.1.4.1 2009-06-29 13:22:25 kchalupa Exp $

#endregion
