USE [master]
GO

-- ==================================
-- Drop the Security database first
-- ===================================
IF EXISTS (SELECT * FROM master.dbo.sysdatabases WHERE name = N'Security')
  PRINT 'Dropping [Security] Database'
  DROP DATABASE [Security]
GO


-- ===============================
-- Create the Security database
-- ===============================

PRINT 'Creating [Security] Database'

-- Create
CREATE DATABASE [Security]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Security', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.V3DENT\MSSQL\DATA\Security.mdf' , SIZE = 11264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Security_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.V3DENT\MSSQL\DATA\Security_log.ldf' , SIZE = 12032KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

EXEC [Security].sys.sp_addextendedproperty @name=N'Viatronix', @value=N'True' 
GO
EXEC [Security].sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Contains all user security for the V3D Enterprise System' 
GO


ALTER DATABASE [Security] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Security].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Security] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [Security] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Security] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Security] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Security] SET ARITHABORT ON 
GO

ALTER DATABASE [Security] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Security] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Security] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Security] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Security] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Security] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Security] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Security] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Security] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Security] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Security] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Security] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Security] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Security] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [Security] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Security] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Security] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Security] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Security] SET RECOVERY FULL 
GO

ALTER DATABASE [Security] SET  MULTI_USER 
GO

ALTER DATABASE [Security] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [Security] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Security] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Security] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Security] SET  READ_WRITE 
GO

