USE [master]
GO

-- ==================================
-- Drop the Storage database first
-- ===================================
IF EXISTS (SELECT * FROM master.dbo.sysdatabases WHERE name = N'Storage')
  PRINT 'Dropping [Storage] Database'
  DROP DATABASE [Storage]
GO


-- ===============================
-- Create the Storage database
-- ===============================

PRINT 'Creating [Storage] Database'

-- Create
CREATE DATABASE [Storage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Storage', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.V3DENT\MSSQL\DATA\Storage.mdf' , SIZE = 16640KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Storage_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.V3DENT\MSSQL\DATA\Storage_log.LDF' , SIZE = 768KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

EXEC [Storage].sys.sp_addextendedproperty @name=N'Viatronix', @value=N'True' 
GO
EXEC [Storage].sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Contains all received and processed data within the V3D Enterprise System' 
GO

ALTER DATABASE [Storage] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Storage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Storage] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [Storage] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Storage] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Storage] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Storage] SET ARITHABORT ON 
GO

ALTER DATABASE [Storage] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Storage] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Storage] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Storage] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Storage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Storage] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Storage] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Storage] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Storage] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Storage] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Storage] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Storage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Storage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Storage] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [Storage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Storage] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Storage] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Storage] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Storage] SET RECOVERY FULL 
GO

ALTER DATABASE [Storage] SET  MULTI_USER 
GO

ALTER DATABASE [Storage] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [Storage] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Storage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Storage] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Storage] SET  READ_WRITE 
GO

