// $Id: vxRendererAlphaActiveRange.h,v 1.1.1.1 2004/03/02 03:58:41 geconomos Exp $
//
// Copyright © 2002, Viatronix Inc., All Rights Reserved.
//
// This is PROPRIETARY SOURCE CODE of Viatronix Inc. The contents of this file
// may not be disclosed to third parties, copied or duplicated in any form, 
// in whole or in part, without the prior written permission of Viatronix Inc. 
//
// Author: Ingmar Bitter (mailto:ingmar@viatronix.com)

/**
 *  This class defines the Alpha active range
 */

#ifndef vxRendererAlphaActiveRange_h
#define vxRendererAlphaActiveRange_h


// includes
#include "vxRendererSoftware.h"


// forward declarations
class vxControlPoint;


// class definition
class VX_VIEWER_DLL vxRendererAlphaActiveRange: public vxRendererSoftware
{
// functions
public:

  // constructor
  vxRendererAlphaActiveRange(vxEnvironment & environment);

  // destructor
  virtual ~vxRendererAlphaActiveRange() {};

  /// called when this object is initialized
  virtual void Initialize();

  /// perform pre-rendering operations
  virtual int4 PreRender();

  /// this event handler is called when the OpenGL drawing should take place
  virtual void Render();

  /// draw the texture of the image generated by the algorithm
  virtual void DrawTexture();

  /// draw the window/level
  void DrawWindowLevel();

  /// generate the histogram texture
  void GenerateHistogramTexture();

}; // vxRendererAlphaActiveRange


#endif // vxRendererAlphaActiveRange_h


// Revision History:
// $Log: vxRendererAlphaActiveRange.h,v $
// Revision 1.1.1.1  2004/03/02 03:58:41  geconomos
// Moved and restructured code from the old xp module. This helps 
// recompiling everything in one go and also reduces the compile
// time for the individual projects due to the new library structure.
//
// Revision 1.12  2003/08/20 14:22:15  michael
// added "mailto:"
//
// Revision 1.11  2003/07/30 18:49:14  michael
// replaced active rendering from histogram to a texture based rendering of the
// histogram where the texture is only updated when the histogram is modified.
//
// Revision 1.10  2003/07/29 11:05:08  michael
// replaced redundant code by one centralized piece that draws the histogram.
// However, it is still actively drawn but should use a texture that is only updated
// if the BaseHistogram has changed ...
//
// Revision 1.9  2003/05/19 14:37:43  frank
// Removed unused return parameter
//
// Revision 1.8  2003/05/17 15:44:49  michael
// reformatting
//
// Revision 1.7  2003/05/16 13:22:14  frank
// formatting
//
// Revision 1.6  2003/05/14 18:30:03  dongqing
// code review
//
// Revision 1.5  2003/05/14 16:10:20  michael
// code review
//
// Revision 1.4  2002/10/17 22:16:47  geconomos
// Removed VX_VIEWER_DLL from class specification
//
// Revision 1.3  2002/09/10 23:06:13  frank
// Made alpha curve manipulation possible.
//
// Revision 1.2  2002/09/10 20:37:55  michael
// Fixed "foreward" --> "forward"
//
// Revision 1.1  2002/09/06 23:06:17  ingmar
// new TFE without sampling effect renderer
//
// $Header: /CVS/cvsRepository/V3D/src/vxViewer/include/vxRendererAlphaActiveRange.h,v 1.1.1.1 2004/03/02 03:58:41 geconomos Exp $
// $Id: vxRendererAlphaActiveRange.h,v 1.1.1.1 2004/03/02 03:58:41 geconomos Exp $
