// $Id: vxRendererSoftwareMPRCurved.h,v 1.1 2006/08/17 14:02:36 gdavidson Exp $
//
// Copyright © 2002, Viatronix Inc., All Rights Reserved.
//
// This is PROPRIETARY SOURCE CODE of Viatronix Inc. The contents of this file
// may not be disclosed to third parties, copied or duplicated in any form, 
// in whole or in part, without the prior written permission of Viatronix Inc. 
//
// Owner: Frank Dachille (frank@viatronix.com)


// pragmas
#pragma once


// includes
#include "vxRendererSoftwareMPR.h"


/**
 * Renders a curved MPR view.
 */
class VX_VIEWER_DLL vxRendererSoftwareMPRCurved : public vxRendererSoftwareMPR
{
// member functions
public:

  /// constructor
  vxRendererSoftwareMPRCurved( vxEnvironment & environment );
 
  /// destructor
  virtual ~vxRendererSoftwareMPRCurved();

  /// has something changed that makes redrawing necessary?
  virtual bool IsRedrawNecessary();

  /// perform pre-rendering operations
  virtual int4 PreRender();
  
  /// this is ONLY for image space parallel algorithms
  virtual int4 RenderWindow( const BoundingRect<uint2> & renderWindow, const uint1 & uThreadID );

  /// set the texture of the image generated by the algorithm
  virtual void DrawTexture();

  /// returns the desired size of the rendered image
  static Triple<uint4> GetDesiredImageSize( const uint4 uViewportWidth, const uint4 uViewportHeight );

protected:

  /// Setup the ends of the scanline
  virtual void SetupScanlines();

private:
  
  /// render a MIP slab
  int4 RenderMIP( const BoundingRect<uint2> & renderWindow, vxEnvironment & renderEnv, bool bSlab = false );  

  /// render a single thin slice
  int4 RenderSingleLayer( const BoundingRect<uint2> & renderWindow, vxEnvironment & renderEnv );

  /// render an x-ray slab
  int4 RenderXRay( const BoundingRect<uint2> & renderWindow, vxEnvironment & renderEnv );

  /// copy constructor
  vxRendererSoftwareMPRCurved(const vxRendererSoftwareMPRCurved &);                   // should only be public if really implemented!
  
  /// assignment operator
  const vxRendererSoftwareMPRCurved & operator=(const vxRendererSoftwareMPRCurved &); // should only be public if really implemented!
  
private:

  /// ????????????????????????????????????????????
  const float4 m_fMPRRenderSamplingStep;

  /// a cached copy of the last window size
  vxWinRect m_lastWinRect;

}; // class vxRendererSoftwareMPRCurved


// $Log: vxRendererSoftwareMPRCurved.h,v $
// Revision 1.1  2006/08/17 14:02:36  gdavidson
// Moved CurvedMPR to vxViewer
//
// Revision 1.2  2004/12/22 14:12:15  frank
// formatting
//
// Revision 1.1  2004/08/09 19:29:34  frank
// first version in new V3D Viewer
//
// Revision 1.1.1.1  2004/03/02 03:58:39  geconomos
// Moved and restructured code from the old xp module. This helps 
// recompiling everything in one go and also reduces the compile
// time for the individual projects due to the new library structure.
//
// Revision 1.7  2004/01/13 14:53:13  frank
// Fixed problem with lack of update when toggling full screen mode of curved mpr view
//
// Revision 1.6  2003/12/18 17:05:32  frank
// Optimizing redraws
//
// Revision 1.5  2003/12/15 16:09:10  frank
// Issue #3569: Initialized the oblique and curved views from annotations
//
// Revision 1.4  2003/11/18 15:54:03  wenli
// 3D Biconvex Slab MIP
//
// Revision 1.3  2003/07/24 17:53:53  michael
// Changed RenderWindow() to pass in thread ID so that the progress of a
// multi-threaded rendering can be monitored
//
// Revision 1.2  2003/05/21 17:51:56  frank
// code review
//
// Revision 1.1  2003/05/08 19:59:27  geconomos
// Moved from Viatronix.Viewers.Explorer.Plugins.CTA
//
// Revision 1.7  2003/05/02 15:25:59  frank
// code review
//
// Revision 1.6  2003/03/05 13:52:25  frank
// Added New Cine Series
//
// Revision 1.5  2003/02/13 17:16:55  jmeade
// Merge-to-Main_BeforeBranch_VC_1-3_to_UpdateAfterBranch_VC_1-3.
//
// Revision 1.4  2003/02/11 20:07:25  frank
// Moved function to CurvedProjected
//
// Revision 1.3.2.1  2003/02/12 23:10:18  jmeade
// Merged changes between main-branch tags "BeforeBranch_VC_1-3" and "UpdateAfterBranch_VC_1-3" that should've been in VC_1-3 branch.
//
// Revision 1.3  2002/11/13 02:16:28  frank
// formatting
//
// Revision 1.2  2002/11/11 20:10:16  frank
// Applied antialiasing to the centerline.
//
// Revision 1.1  2002/10/31 12:46:52  geconomos
// Moved from Viatronix.Visualization.Ext.Vascular
//
// Revision 1.2  2002/08/15 18:20:36  wenli
// initial version - Vascular
//
// Revision 1.1  2002/08/15 14:26:58  wenli
// initial version - Vascular
//
// Revision 1.3.2.4  2002/05/23 18:45:13  frank
// Moved to Ribbon data structure.
//
// Revision 1.3.2.3  2002/05/21 22:24:28  frank
// Improved a lot.
//
// Revision 1.3.2.2  2002/05/15 16:22:17  frank
// Cleaned up image sizes.
//
// Revision 1.3.2.1  2002/05/13 20:37:13  frank
// Formatting.
//
// Revision 1.3  2002/04/23 21:35:32  jenny
// not a template class any more
//
// Revision 1.2  2002/04/11 14:38:30  michael
// added missing private copy constructor and assignment operator
//
// $Header: /CVS/cvsRepository/V3D/src/vxViewer/include/vxRendererSoftwareMPRCurved.h,v 1.1 2006/08/17 14:02:36 gdavidson Exp $
// $Id: vxRendererSoftwareMPRCurved.h,v 1.1 2006/08/17 14:02:36 gdavidson Exp $
