// $Id: vxRendererSoftwareMPROblique.h,v 1.4 2007/02/15 00:08:24 jmeade Exp $
//
// Copyright © 2002, Viatronix Inc., All Rights Reserved.
//
// This is PROPRIETARY SOURCE CODE of Viatronix Inc. The contents of this file
// may not be disclosed to third parties, copied or duplicated in any form, 
// in whole or in part, without the prior written permission of Viatronix Inc. 
//
// Owner: Frank Dachille (frank@viatronix.ncom)


// pragmas
#pragma once


// includes
#include "vxRendererSoftwareMPR.h"


/**
 * Renders an oblique MPR slice based on a camera and plane.
 */
class VX_VIEWER_DLL vxRendererSoftwareMPROblique : public vxRendererSoftwareMPR
{
// functions
public:

  /// constructor
  vxRendererSoftwareMPROblique( vxEnvironment & environment );
 
  /// destructor
  virtual ~vxRendererSoftwareMPROblique() {}

  /// perform pre-rendering operations
  virtual int4 PreRender();

  /// this is ONLY for image space parallel algorithms
  virtual int4 RenderWindow( const BoundingRect<uint2> & window, const uint1 & uThreadID );

  /// returns the size of the image to be computed
  virtual Triple<uint2> GetImageSize();

  /// set the texture of the image generated by the algorithm
  virtual void DrawTexture();
  
  /// retrieve the corner points in world coordinates
  Point3Df * GetCornerPoints() { return reinterpret_cast< Point3Df * > ( m_cornerIntersection ); }

private:

  /// computes the four corner points for the oblique quad
  bool ComputeFourCornerPoints();

  /// copy constructor
  vxRendererSoftwareMPROblique( const vxRendererSoftwareMPROblique & other);                    // should only be public if really implemented!

  /// assignment operator
  const vxRendererSoftwareMPROblique & operator =( const vxRendererSoftwareMPROblique & other); // should only be public if really implemented!

  /// helper function to determine if the ray position is within a box
  bool IsInsideBox( vxBlockVolumeRayIterator<uint2> & iter, Box<float> & box ) const;

// data
private:

  /// the intersection points of the camera view frustum and the oblique plane.
  Point3Df m_cornerIntersection[4];

}; // class vxRendererSoftwareMPROblique


// $Log: vxRendererSoftwareMPROblique.h,v $
// Revision 1.4  2007/02/15 00:08:24  jmeade
// Merge_from_VC_2-0_on_070214
//
// Revision 1.3.12.1  2006/05/05 13:05:41  geconomos
// added virtual destructors
//
// Revision 1.3  2001/01/01 16:09:38  frank
// formatting
//
// Revision 1.2  2004/04/21 20:03:33  geconomos
// Added an accessor for the four corner points.
//
// Revision 1.1.1.1  2004/03/02 03:58:41  geconomos
// Moved and restructured code from the old xp module. This helps 
// recompiling everything in one go and also reduces the compile
// time for the individual projects due to the new library structure.
//
// Revision 1.14  2003/09/25 13:32:48  frank
// Added crop box handling in oblique view
//
// Revision 1.13  2003/09/25 03:06:35  frank
// Merged oblique views into one
//
// Revision 1.10  2003/09/04 17:29:45  michael
// merged the branch "XP1_1" back into the trunc
//
// Revision 1.9  2003/08/20 14:11:35  michael
// removed empty for loop
//
// Revision 1.8.2.1  2003/08/11 19:08:16  michael
// fixed issue #3261
//
// Revision 1.8  2003/07/24 17:53:53  michael
// Changed RenderWindow() to pass in thread ID so that the progress of a
// multi-threaded rendering can be monitored
//
// Revision 1.7  2003/05/27 14:12:00  michael
// completed code review
//
// Revision 1.6  2003/05/22 13:11:47  frank
// code review
//
// Revision 1.5  2003/05/21 18:26:04  frank
// code review
//
// Revision 1.4  2003/05/17 15:44:51  michael
// reformatting
//
// Revision 1.3  2002/12/17 18:43:47  frank
// Moved oblique corner computation into shared area so others can use it.
//
// Revision 1.2  2002/12/09 15:32:29  michael
// Added comments and code clean-up
//
// Revision 1.1  2002/11/19 21:25:15  michael
// added initial version of this renderer
//
// Revision 1.10  2002/11/13 20:11:43  frank
// enabled oblique view renderer and manipulator
//
// Revision 1.9  2002/11/05 19:54:12  frank
// Created helper function for producing the Quadrilateral for the oblique slice plane.
//
// Revision 1.8  2002/10/17 22:16:47  geconomos
// Removed VX_VIEWER_DLL from class specification
//
// Revision 1.7  2002/10/17 15:34:40  frank
// Cleaning up oblique renderer.
//
// Revision 1.6  2002/08/09 15:40:05  uday
// Replaced Rect<> by BoundingRect<>.
//
// Revision 1.5  2002/07/02 20:45:00  geconomos
// Exporting classes .
//
// Revision 1.4  2002/04/23 21:35:53  jenny
// not a template class any more
//
// Revision 1.3  2002/04/23 15:40:28  jenny
// got rid of Demo()
//
// Revision 1.2  2002/04/11 14:38:30  michael
// added missing private copy constructor and assignment operator
//
// $Header: /CVS/cvsRepository/V3D/src/vxViewer/include/vxRendererSoftwareMPROblique.h,v 1.4 2007/02/15 00:08:24 jmeade Exp $
// $Id: vxRendererSoftwareMPROblique.h,v 1.4 2007/02/15 00:08:24 jmeade Exp $
