//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by E:\SVN\VC_4-1\src\vc\Viatronix.Colon.French\ViatronFRA.rc
//
#define IDR_MANIFEST                    1
#define RT_MANIFEST                     24
#define IDD_ABOUTBOX                    100
#define IDD_VDB_DIALOGBAR               101
#define IDDB_SLICE_VIEW                 102
#define IDC_POINTER_WAIT                103
#define IDR_VIATRON                     104
#define IDB_TABSTRIP                    105
#define IDD_SELECTSERIESDIALOG          108
#define IDR_MAINFRAME                   128
#define IDD_CONTROLS_HORIZONTAL         129
#define IDS_V3DVIEWER_COLON             130
#define IDD_CONTROLS_VERTICAL           131
#define IDS_V3DCONSOLE                  132
#define IDB_V3D_COLON_ABOUT             133
#define IDD_SPLASH_SCREEN               134
#define IDDB_NAVIGATION                 135
#define IDM_VIEW_OPTION_POPUPS          136
#define IDB_RPT_LIST                    137
#define IDR_CONTROLS                    138
#define IDI_WINDOWLEVEL                 139
#define IDD_VIEW_SELECT                 140
#define IDDB_OVERVIEW                   141
#define IDC_INDEXHAND                   142
#define IDM_VIEW_WINDOW                 143
#define IDC_HIGHLIGHTS                  144
#define IDI_RESET_WINDOWLEVEL           145
#define IDC_CROSSMC                     146
#define IDC_SCROLLUP                    147
#define IDC_SCROLLDOWN                  148
#define IDC_SCROLL                      149
#define IDC_MEASURE                     150
#define IDM_WLPRESETS                   151
#define IDD_PATIENT_INFO_HORIZONTAL     152
#define IDM_BOOKMARK_POPUP              153
#define IDC_WINDOWLEVEL                 154
#define IDD_DBSEARCH                    155
#define IDM_REPORT_ENTRY_POPUP          156
#define IDM_SLICE_VIEW_WINDOW           157
#define IDD_SEARCH_DATES                158
#define IDB_CHAIN_LINK                  159
#define IDB_LEFTMOUSE                   160
#define IDB_RIGHTMOUSE                  161
#define IDB_MIDMOUSE                    162
#define IDB_LEFT_ARROW                  163
#define IDB_RIGHT_ARROW                 164
#define IDB_PRONE_SMALL                 165
#define IDB_SUPINE_SMALL                166
#define IDB_MEASURE                     167
#define IDB_FLIPVIEW                    168
#define IDB_TRANSLUCENT_OVERVIEW        169
#define IDB_CROSS_SECTIONAL             170
#define IDB_METALSKIN                   171
#define IDB_GREYEDGE                    172
#define IDB_RESET_OVERVIEW              173
#define IDB_HIGHLIGHTS                  174
#define IDB_AUTOFLY                     175
#define IDB_TRANSPARENT_VIEW            176
#define IDB_TOOLS                       177
#define IDB_TO_RECTUM_ARROW             178
#define IDB_TO_CECUM_ARROW              179
#define IDM_SLICE_ORIENTATION           180
#define IDM_SLICE_CROSS_SECTION_ORIENTATION 181
#define IDB_STEELSKIN                   182
#define IDB_BLUEMETAL                   183
#define IDD_USR_ACCOUNTMANAGER          184
#define IDD_USR_EDITACCOUNT             185
#define IDP_PREFS_NETWORK               186
#define IDP_PREFS_GENERAL               187
#define IDP_PREFS_REPORT                188
#define IDC_MAGNIFY                     189
#define IDM_SLICE_ZOOM                  190
#define IDM_OVERVIEW                    191
#define IDC_PAN                         192
#define IDD_RPT_COLON_FINDINGS          193
#define IDB_RPT_GROUP_24                194
#define IDD_RPT_OTHER_FINDINGS          195
#define IDD_RPT_SUB_LUNG1               196
#define IDD_RPT_SUB_LUNG2               197
#define IDD_RPT_SUB_LIVER1              198
#define IDD_RPT_SUB_VASCULAR1           199
#define IDD_RPT_SUB_ADRENAL1            200
#define IDD_RPT_SUB_RENAL1              201
#define IDD_RPT_SUB_RENAL2              202
#define IDD_RPT_SUB_SPLEEN1             203
#define IDD_RPT_SUB_VASCULAR2           204
#define IDD_RPT_NON_DISTENDED           205
#define IDM_REPORT_POPUPS               206
#define IDD_RPT_PREVIEW                 207
#define IDD_DBINFO                      208
#define IDD_RPT_SUB_OTHER               209
#define IDD_RPT_SUB_RENAL3              210
#define IDD_TRANSFER                    211
#define IDD_RPT_MISC                    212
#define IDD_RPT_SUB_GI1                 213
#define IDB_SEGJUMP_CECUM_PREV          214
#define IDB_SEGJUMP_CECUM_NEXT          215
#define IDB_SEGJUMP_RECTUM_PREV         216
#define IDB_SEGJUMP_RECTUM_NEXT         217
#define IDB_LISTHDR_SORTUP              218
#define IDB_LISTHDR_SORTDN              219
#define IDW_SNAPSHOT                    220
#define IDW_BLASTER                     221
#define IDW_BOOKMARK_DROP               222
#define IDW_EXPLOSION                   223
#define IDB_CAMERA                      224
#define IDI_PUSHPIN                     225
#define IDA_TRANSFER_FROM_NET           226
#define IDM_STUDYBROWSER_ITEM           227
#define IDD_BLANK                       228
#define IDM_DATABASE_LOCATIONS          229
#define IDM_V3DCONSOLE                  231
#define IDB_OVERVIEW_DLGBAR             232
#define IDB_ENDOVIEW_HORIZ_DLGBAR       233
#define IDB_PATIENTINFO_HORIZ_BKGD      234
#define IDB_BUTTON_SQUARE               235
#define IDB_MISSEDREGIONS_NEXT          236
#define IDB_OVERVIEW_MARKING            237
#define IDB_ENDOVIEW_MARKING            238
#define IDB_MISSEDREGIONS_DETECT        239
#define IDT_VERIFICATION                240
#define IDT_REGISTRATION                241
#define IDT_STANDARDVIEW                242
#define IDT_ENDOSLICE                   243
#define IDD_PATIENT_INFO_VERTICAL       244
#define IDB_SCROLLBARIMAGES             245
#define IDB_ENDOVIEW_VERT_DLGBAR        246
#define IDB_PATIENTINFO_VERT_BKGD       247
#define IDB_SLICEOPTIONS                249
#define IDB_BUTTON_LARGE                250
#define IDB_BUTTON_MEDIUM               251
#define IDB_BUTTON_SMALL                252
#define IDC_RECORDING_MOVIE             253
#define IDT_DUALORTHOGONAL              254
#define IDT_DUALOVERVIEW                255
#define IDB_MOVIEHEADER                 256
#define IDR_TOOLBAR1                    258
#define IDB_MOVIE_BUTTON                259
#define IDD_TRANSFER_DEST               262
#define IDC_SNAPSHOT                    263
#define IDB_V3DAPP_BUTTON               264
#define IDT_2DSEGMENTS                  265
#define IDB_COMBOBUTTON_MEDIUM          266
#define IDM_STUDYINFO_ITEM              267
#define IDM_TOOLS                       268
#define IDM_OVERVIEW_INDICATORS         269
#define IDM_ENDOVIEW_INDICATORS         270
#define IDC_THUMBNAIL                   271
#define IDB_ANNOTATIONS_BUTTON          272
#define IDM_ANNOTATION_POPUP            273
#define IDM_USERREGISTRATION_POPUP      274
#define IDT_3DSEGMENTS                  275
#define IDM_TOOLS_PLUS                  276
#define IDT_PANE_OVERVIEW_PRIMARY       277
#define IDB_SLIDINGPANEHEADER           278
#define IDB_SLIDINGPANEHEADER_UP        279
#define IDB_DATASET_LINK                280
#define IDB_SP_SUPINE_BUTTON            281
#define IDB_SP_PRONE_BUTTON             282
#define IDD_MOVIE_CREATION              283
#define IDD_NOTATIONS                   284
#define IDB_SLIDINGPANEHEADER_DN        285
#define IDB_DELETEALL_BUTTON            286
#define IDB_ANNOTATIONS_BUTTON_SMALL    287
#define IDB_BOOKMARKS_BUTTON_SMALL      288
#define IDC_ANNOTATION                  289
#define IDD_PICKSCREENPOINT             290
#define IDC_POINTER_PAINTCAN            291
#define IDI_VIDEOCAMERA                 292
#define IDB_MEASUREMENTS_BUTTON_SMALL   293
#define IDD_ADJUST_TRANSLUCENCY         294
#define IDB_COLORMAP_RESET_SYSTEM       295
#define IDB_COLORMAP_RESET_USER         296
#define IDR_MAINFRAME_CONSOLE           297
#define IDB_SEGMENT_POLYP               298
#define IDB_PREPOST_POSTCONTRAST_BTN    299
#define IDB_PREPOST_PRECONTRAST_BTN     300
#define IDB_BUTTON_XLARGE               301
#define IDM_SLICE_RENDERMODE            302
#define IDT_DUALORTHOGONAL2             303
#define IDR_MAINFRAME_REGISTRATION      303
#define IDM_OVERVIEW_ABBREV             304
#define IDB_STATE_CHECKBOX_24           305
#define IDB_SHOWREGION_SM               306
#define IDB_NEXTREGION_SM               307
#define IDB_BKGND_SIDE_RIGHT            308
#define IDB_BKGND_CORNER_BOTTOM_LEFT    309
#define IDB_BKGND_CORNER_BOTTOM_RIGHT   310
#define IDB_BKGND_CORNER_TOP_LEFT       311
#define IDB_BKGND_SIDE_BOTTOM           312
#define IDR_PNG6                        313
#define IDB_BKGND_SIDE_LEFT             313
#define IDB_TAB_INACTIVE_RIGHT          314
#define IDB_SIDE_TAB_ACTIVE_END         315
#define IDB_SIDE_TAB_ACTIVE_LEFT        316
#define IDB_SIDE_TAB_ACTIVE_MIDDLE      317
#define IDB_SIDE_TAB_ACTIVE_RIGHT       318
#define IDB_SIDE_TAB_INACTIVE_END       319
#define IDB_SIDE_TAB_INACTIVE_LEFT      320
#define IDR_PNG9                        321
#define IDB_SIDE_TAB_INACTIVE_MIDDLE    321
#define IDB_SIDE_TAB_INACTIVE_RIGHT     322
#define IDB_TAB_ACTIVE_END              323
#define IDB_TAB_ACTIVE_LEFT             324
#define IDB_TAB_ACTIVE_MIDDLE           325
#define IDB_TAB_ACTIVE_RIGHT            326
#define IDB_TAB_INACTIVE_END            327
#define IDB_TAB_INACTIVE_LEFT           328
#define IDB_TAB_INACTIVE_MIDDLE         329
#define IDM_CADFINDING_POPUP            330
#define IDB_CADRES_DLG                  331
#define IDB_LOGO_REGISTRATION_VIEW      332
#define IDB_BKGND_HEADER_RIGHT          333
#define IDB_BKGND_HEADER_LEFT           334
#define IDR_PNG3                        335
#define IDB_MENUBAR_RIGHT               335
#define IDB_BKGND_HEADER_MIDDLE         336
#define IDB_FINDING_ACCEPT              337
#define IDB_FINDING_REJECT              338
#define IDB_FINDING_UNDECIDED           339
#define IDR_FINDING_ACCEPT              340
#define IDM_SERIES_SELECT               340
#define IDB_VIATRONIX_CAD               341
#define IDB_NEXT_CAD_FINDING            342
#define IDB_DETECT_CAD_FINDINGS         343
#define IDB_DATASET_LINK_VERTICAL       344
#define IDB_MENUBAR_LEFT                346
#define IDB_MENUBAR_MIDDLE              347
#define IDM_OVERVIEW_RESET              348
#define IDB_DATASET_UNLINK              349
#define IDB_DATASET_UNLINK_VERTICAL     350
#define IDB_BITMAP1                     351
#define IDB_CHAIN_UNLINK                352
#define IDB_V3D_COLON_LOGIN             353
#define IDB_VIATRONIX_LOGO              354
#define IDC_POINTER_PAINTCAN_NEW        355
#define IDC_POINTER_PAINTCAN_DEL        356
#define IDC_POINTER_PAINTCAN_ADD        357
#define IDC_POINTER_PAINTCAN_REM        358
#define IDM_ROI_EDIT_TOOLS              359
#define IDB_DASHBOARD_BKGD              360
#define IDB_PATIENTINFO_HORIZ_BKGD_WIDESCREEN 361
#define IDB_BKGND_HEADER_RIGHT_WIDESCREEN 362
#define IDB_SLIDER_THUMB                363
#define IDB_SLIDER_BKGD                 364
#define IDD_MISSED_REGIONS              365
#define IDB_ROIMEASURE                  366
#define IDB_REGIONEDIT_BTNBAR           367
#define IDB_REGIONSIZE_BTNBAR           368
#define IDB_BUTTON_SMALL_RIGHT          369
#define IDM_OVERVIEW_ABBREV_PLUS_DISSECTION 370
#define IDB_LINKED_UNLINKED             371
#define IDB_BKGND_SIDE_TOP              379
#define IDD_PROGRESS                    385
#define IDD_PROGRESS_DLG                385
#define IDB_CHECK_MARK                  387
#define IDC_VDB_STATUS                  1000
#define IDC_EDIT1                       1001
#define IDC_IMAGES                      1002
#define IDC_EDIT2                       1002
#define IDC_PRIMARY_PREPROCESSED_SERIES 1002
#define IDC_VIEW_SELECT_TABCTRL         1003
#define IDC_EDIT3                       1003
#define IDC_PRIMARY_CAD_SERIES          1003
#define IDC_VDB_PROGRESS                1004
#define IDC_EDIT4                       1004
#define IDC_SECONDARY_VOLUME_SERIES     1004
#define IDC_ENTRY_NAME                  1005
#define IDC_EDIT5                       1005
#define IDC_SECONDARY_PREPROCESSED_SERIES 1005
#define IDC_CDB_MEASURE_RADIO           1006
#define IDC_EDIT6                       1006
#define IDC_SECONDARY_CAD_SERIES        1006
#define IDC_LINE                        1007
#define IDC_SESSION_SERIES              1007
#define IDC_CTRLS_SPEED_SLIDER          1008
#define IDC_VSP_PROGRESS                1009
#define IDC_VSP_PROGRESS_TEXT           1010
#define IDC_CDB_HIGHLIGHTS_RADIO        1011
#define IDC_CDB_WINDOWLEVEL_RADIO       1012
#define IDC_ENTRIES                     1014
#define IDC_CDB_AUTOFLY_RADIO           1015
#define IDC_CDB_VIEWDIRECTION_BTN       1016
#define IDC_CDB_FLIPVIEW_BTN            1017
#define IDC_CTRLS_SLIDER_VALUE_DISP     1018
#define IDC_CDB_DETECTMISSEDRGNS_BTN    1019
#define IDC_CDB_NEXTMISSEDRGN_BTN       1020
#define IDC_SPIN_SIZE1                  1021
#define IDC_ODB_RESET_OVERVIEW          1022
#define IDC_SPIN_SIZE2                  1023
#define IDC_SDB_RESET_WINDOW_LEVEL      1024
#define IDC_SDB_WINDOWLEVEL_MODE        1025
#define IDC_SPIN_SIZE3                  1026
#define IDC_CDB_PAINTING                1027
#define IDC_CDB_ORTHOGONAL_SHADOWS      1028
#define IDC_CDB_CROSS_SECTIONAL_SHADOW  1029
#define IDC_ODB_SLICE_INDICATORS        1030
#define IDC_ODB_TRANSLUCENT             1031
#define IDC_PID_PATIENTNAME             1032
#define IDC_PID_PATIENTDATA             1033
#define IDC_PID_EXAMSITE                1034
#define IDC_PID_PHYSICIANNAME           1035
#define IDC_PID_EXAMTIME                1036
#define IDC_PID_PATIENTID               1037
#define IDC_VSD_PROGRESS                1038
#define IDC_VSD_LEFTBUTTON_TEXT         1039
#define IDC_VSD_MIDBUTTON_TEXT          1040
#define IDC_VSD_RIGHTBUTTON_TEXT        1041
#define IDC_CDB_MISSEDRGN_LIST          1042
#define IDC_ODB_SHOWHIDE                1043
#define IDC_CDB_SEGMENT_JUMP_CONTROL    1044
#define IDS_LOGIN_FAILED                1044
#define IDC_CDB_SEGMENT_JUMP_PREV       1045
#define IDC_CDB_SEGMENT_JUMP_DIRECTION  1046
#define IDC_CDB_SEGMENT_JUMP_NEXT       1047
#define IDC_NDB_TAB                     1048
#define IDC_OTHERFINDING_LIST           1049
#define IDC_CDB_REGIONSEGMENT_BTN       1050
#define IDC_VSD_CTRL                    1200
#define IDC_VSD_SHIFT                   1201
#define IDC_OVERVIEW_FRAME              1202
#define IDC_MAXIMUM_SIZE                1203
#define IDC_PERP_SIZE                   1204
#define IDC_NAME                        1205
#define IDC_COMMENTS                    1206
#define IDC_ID                          1207
#define IDC_LENGTH_SIZE                 1208
#define IDC_COMMENTS2                   1209
#define IDC_SEX                         1210
#define IDC_COMMENTS3                   1211
#define IDC_PHYSICIAN                   1212
#define IDC_DATE                        1213
#define IDC_AGE                         1214
#define IDC_ODB_TOGGLE_OVERVIEW_MARKING 1215
#define IDC_AUTHOR                      1216
#define IDC_CDB_MODES_BUTTON            1217
#define IDC_CDB_MODES                   1218
#define IDC_CDB_AUTOFLY                 1219
#define IDC_TYPE                        1220
#define IDC_UNIT                        1221
#define IDC_CDB_TOOLS                   1222
#define IDC_PID_SUPINEPRONE_BTN         1223
#define IDC_CDB_SNAPSHOT                1224
#define IDC_PID_REGISTRATION_LINKBTN    1224
#define IDC_CDB_MOVIE                   1225
#define IDC_DBS_IDTEXT                  2001
#define IDC_DBS_REFERTEXT               2002
#define IDC_DBS_FIRSTNAMETEXT           2003
#define IDC_DBS_LASTNAMETEXT            2004
#define IDC_DBS_CHKDBUNREAD             2005
#define IDC_DBS_SEARCHTEXT              2006
#define IDC_DBS_SEARCHRESTEXT           2007
#define IDC_DBS_CLEARSEARCH             2008
#define IDC_DB_CALFROM                  2009
#define IDC_DB_SELFROMTEXT              2010
#define IDC_DBS_DATEPICKER              2011
#define IDC_DBS_INFO                    2012
#define IDC_DBS_OPENREPORT              2013
#define IDC_DBS_LOCATION_DISPLAY        2014
#define IDC_DBS_RESLIST                 2015
#define IDC_DBS_OPENSTUDY               2016
#define IDC_DBS_DELETE                  2017
#define IDC_DBS_TRANSFER                2018
#define IDC_DBI_OPENSTUDY               2019
#define IDC_DBI_RESLIST                 2020
#define IDC_DBI_DELETE                  2021
#define IDC_DBI_TRANSFER                2022
#define IDC_DBI_SINFO_TITLE             2023
#define IDC_DBI_IDONE                   2024
#define IDC_DBI_SINFO_LOCATIONS         2025
#define IDC_DBI_CANCEL_TRANSFER         2026
#define IDC_USR_EDPASS                  2028
#define IDC_USR_EDPASSV                 2029
#define IDC_USR_EDNAME                  2030
#define IDC_USR_ADD                     2031
#define IDC_USR_EDOLDPASS               2032
#define IDC_USR_EDFULLNAME              2033
#define IDC_USR_REMOVE                  2034
#define IDC_USR_PROPS                   2035
#define IDC_USR_USERLIST                2036
#define IDC_USR_ACCESSTYPE              2037
#define IDC_USR_ENABLED                 2038
#define IDC_PREFS_PACSNAME              2039
#define IDC_PREFS_PACSPORT              2040
#define IDC_PREFS_AETITLE               2041
#define IDC_TRANS_LOCAL                 2045
#define IDC_TRANS_CD                    2046
#define IDC_TRANS_PACS                  2047
#define IDC_REPORTPAGE_TOP_MARGIN       2048
#define IDC_REPORTPAGE_BOTTOM_MARGIN    2049
#define IDC_ODB_LOCATION_DISPLAY        2050
#define IDC_VSP_USERNAME_EDIT           2051
#define IDC_VSP_PASSWORD_EDIT           2052
#define IDC_VSP_LOGIN                   2053
#define IDC_VSP_VERSION                 2055
#define IDC_CAPSLOCK_DISP               2056
#define IDC_VSP_CAPSLOCK_DISP           2056
#define IDC_REPORTPAGE_PAGE_NUM_NONE    2057
#define IDC_REPORTPAGE_PAGE_BOTTOM      2058
#define IDC_REPORTPAGE_HEADER_NONE      2059
#define IDC_REPORTPAGE_HEADER_BITMAP    2060
#define IDC_BTN_BITMAP                  2061
#define IDC_BITMAP_FILE                 2062
#define IDC_REPORTPAGE_HEADER_DEFINED   2063
#define IDC_REPORTPAGE_TRANSFER         2064
#define IDC_REPORTPAGE_HEADERTEXT       2065
#define IDC_TRANS_PRIVATE               2071
#define IDC_V1K_VERSION_STATIC          2072
#define IDC_TRANS_TITLE                 2073
#define IDC_TRANS_CANCELTRANSFER        2074
#define IDC_USR_RESET_PASSWORD_CHECK    2075
#define IDC_TRANS_STUDYIDEN             2076
#define IDC_USR_ALLOWMINIMIZE_CHECK     2077
#define IDC_USR_PASSWORDSTATIC          2078
#define IDC_USR_VERIFYSTATIC            2079
#define IDC_USR_ACCESSSTATIC            2080
#define IDC_USR_OLDPASSWORDSTATIC       2081
#define IDC_USR_MUST_CHANGE_PASS_STATIC 2082
#define IDC_DBS_STATUSMESSAGES          2083
#define IDC_TRANS_FUNCTION_STATIC       2084
#define IDC_TRANS_PROGRESS_DISPLAY      2085
#define IDC_TRANS_PROGRESS              2086
#define IDC_TRANS_TIME_REMAIN_DISPLAY   2087
#define IDC_TRANS_TIME_REMAIN_STATIC    2088
#define IDC_USR_MUST_CHANGE_PASS_FRAME  2089
#define IDC_GENERALPAGE_DSNCOMBO        2090
#define IDC_GENERALPAGE_LOGLEVELCOMBO   2091
#define IDC_VSP_PASSWORD_LABEL          2092
#define IDC_VSP_USERNAME_LABEL          2093
#define IDC_TEMPLATE_PATIENTINFO        2094
#define IDC_TEMPLATE_OVERVIEW_SUPINE    2095
#define IDC_TEMPLATE_NOTATIONS          2096
#define IDC_TEMPLATE_OVERVIEW_PRONE     2097
#define IDC_TEMPLATE_ENDOSCOPIC_SUPINE  2098
#define IDC_TEMPLATE_ENDOSCOPIC_PRONE   2099
#define IDC_TEMPLATE_SLICEVIEW_SUPINE   2100
#define IDC_TEMPLATE_SLICEVIEW_PRONE    2101
#define IDC_TEMPLATE_LINKVIEWS          2102
#define IDC_VERIFY_FINISH               2103
#define IDC_VERIFY_SUPINEBACK           2104
#define IDC_VERIFY_PRONEBACK            2105
#define IDC_VERIFY_SUPINEPROMPT         2106
#define IDC_VERIFY_PRONEPROMPT          2107
#define IDC_VERIFY_SUPINELABEL          2108
#define IDC_VERIFY_PRONELABEL           2109
#define IDC_TEMPLATE_OVERVIEW           2110
#define IDC_VERIFY_FINISHPROMPT         2111
#define IDC_TEMPLATE_SLICEVIEW1         2112
#define IDC_VERIFY_NEXT                 2113
#define IDC_TEMPLATE_OVERVIEW2          2114
#define IDC_TEMPLATE_SLICEVIEW2         2115
#define IDC_VERIFY_TITLE                2116
#define IDC_TEMPLATE_SLICEVIEW3         2117
#define IDC_TEMPLATE_SLICEVIEW4         2118
#define IDC_TEMPLATE_OVERVIEWTOOLS      2119
#define IDC_TEMPLATE_CONTROLS           2120
#define IDC_TEMPLATE_ENDOVIEW           2121
#define IDC_TEMPLATE_ADJUSTTRANSLUCENCY 2122
#define IDC_TEMPLATE_DISTFROMRECTUM_DISPLAY 2123
#define IDC_TEMPLATE_DISTFROMRECTUM_LABEL 2124
#define IDC_TEMPLATE_SLICESCROLL1       2125
#define IDC_TEMPLATE_SLICESCROLL2       2126
#define IDC_CUSTOM1                     2127
#define IDC_TEMPLATE_SLICESCROLL3       2128
#define IDC_CUSTOM2                     2129
#define IDC_TEMPLATE_SLICESCROLL4       2130
#define IDC_SUPINELABEL                 2131
#define IDC_PRONELABEL                  2132
#define IDC_DBS_LOCATIONCOMBO           2133
#define IDC_DBS_STUDYTYPECOMBO          2134
#define IDC_FINDING_NORMAL              2135
#define IDC_FINDING_POLYP               2136
#define IDC_FINDING_DIVERTCULUM         2137
#define IDC_FINDING_STENOSIS            2138
#define IDC_FIDNING_OTHER               2139
#define IDC_FINDING_EXTRA_COLONIC       2140
#define IDC_LOCATION_CECUM              2141
#define IDC_LOCATION_ASCENDING          2142
#define IDC_LOCATION_HEPATIC_FLEXURE    2143
#define IDC_LOCATION_TRANSVERSE         2144
#define IDC_LOCATION_SPLENIC_FLEXURE    2145
#define IDC_LOCATION_DESCENDING         2146
#define IDC_LOCATION_SIGMOID            2147
#define IDC_LOCATION_RECTUM             2148
#define IDC_TRANSDEST_FLOPPY            2149
#define IDC_TRANSDEST_CD                2150
#define IDC_DBS_SWITCHTOAPP             2151
#define IDC_GENERALPAGE_TESTCONNECTION  2152
#define IDC_DBS_PREVRESULTS             2153
#define IDC_DBS_NEXTRESULTS             2154
#define IDC_RV_PROGRESS_CTRL_REGCONFIDENCE 2155
#define IDT_CYLINDRICAL_SEGMENTS        2156
#define IDC_PANE_HEADER_STATIC          2157
#define IDC_RSP_PANEHDR_PATIENTINFO     2158
#define IDC_RSP_PANEHDR_SUPINECAD       2159
#define IDC_RSP_PANEHDR_PRONECAD        2160
#define IDC_RSP_PANEHDR_DUALOVERVIEW    2161
#define IDC_RSP_PANEHDR_CONTROLS        2162
#define IDT_PANE_OVERVIEW_DUAL          2163
#define IDC_SLIDING_REGISTRATION_PANE   2164
#define IDC_MCD_FORMAT_COMPRESSNONE     2165
#define IDC_RSP_PANEHDR_NOTATIONS       2166
#define IDC_MCD_FORMAT_COMPRESSLOW      2167
#define IDC_MCD_FORMAT_COMPRESSHIGH     2168
#define IDC_MCD_INCLUDE_OVERVIEW_CHECK  2169
#define IDC_MCD_FORMAT_DESCRIPTION      2170
#define IDC_MCD_PREVIEW_FRAME           2171
#define IDC_NTD_BOOKMARKS_RADIO         2172
#define IDC_NTD_ANNOTATIONS_RADIO       2173
#define IDC_NTD_SUPINE_COMBO            2174
#define IDC_NTD_PRONE_COMBO             2175
#define IDC_NTD_SUPINE_DELETE_BUTTON    2176
#define IDC_NTD_PRONE_DELETE_BUTTON     2177
#define IDC_NTD_DELETEALL_BUTTON        2178
#define IDC_NTD_MEASUREMENTS_RADIO      2179
#define IDC_MCD_FILETITLE_EDIT          2180
#define IDC_RCF_LOCATIONGROUPBOX        2181
#define IDC_AJT_EDITSELECTED            2182
#define IDC_AJT_GRADIENTCTRL            2183
#define IDC_AJT_PEG_VALUE_STATIC        2184
#define IDC_AJT_SAVENEW                 2185
#define IDC_AJT_COLOR_BTN_PREV          2186
#define IDC_AJT_COLOR_BTN_NEXT          2187
#define IDC_CTRLS_PERCEIVED_SPEED_CHECK 2188
#define IDT_MOVIEVIEW_DUAL              2189
#define IDT_MOVIEVIEW_SINGLE            2190
#define IDC_MOVIEVIEW_PROGRESS          2191
#define IDC_STATIC_MOVIEVIEW_TITLE      2192
#define IDC_STATIC_MOVIEVIEW_PROGRESS   2193
#define IDC_TEMPLATE_SLICEVIEW          2194
#define IDC_STATIC_MOVIEVIEW_TIMELEFT   2195
#define IDT_SINGLEORTHOGONAL            2196
#define IDT_FULLOBLIQUE_VIEW            2197
#define IDD_CONTROLS_ABBREV             2198
#define IDD_CAD_RESULTS                 2199
#define IDC_CDR_RESULTLIST              2200
#define IDC_CDR_STATS                   2201
#define IDC_TEMPLATE_CADRESULTSDLG      2202
#define IDC_TEMPLATE_CADRESULTSDLG1     2203
#define IDC_CDR_SHOWFINDINGS            2204
#define IDC_CDR_NEXTFIND                2205
#define IDC_CDR_WARNING                 2206
#define IDC_CDR_VENDORIMAGE             2207
#define IDC_PID_GROUPBOX                2208
#define IDC_TEMPLATE_FLYBOTH            2209
#define IDC_AJT_SAVESELECTED            2210
#define IDC_AJT_CANCELEDIT              2211
#define IDC_AJT_DELETESELECTED          2212
#define IDC_PRIMARY_VOLUME_SERIES_SELECT 2214
#define IDC_PRIMARY_PREPROCESSED_SERIES_SELECT 2215
#define IDC_PRIMARY_CAD_SERIES_SELECT   2216
#define IDC_SECONDARY_VOLUME_SERIES_SELECT 2217
#define IDC_SECONDARY_PREPROCESSED_SERIES_SELECT 2218
#define IDC_SECONDARY_CAD_SERIES_SELECT 2219
#define IDC_PRIMARY_VOLUME_SERIES       2220
#define IDC_SESSION_SERIES_SELECT       2221
#define IDC_SERIES_TABCTL               2222
#define IDC_SELSER_TREE                 2223
#define IDT_REGISTRATION_CAD            2224
#define IDD_CAD_RESULTS_PANE            2225
#define IDD_CONTROLS_VERTICAL_LARGE     2226
#define IDD_CONTROLS_HORIZONTAL_LARGE   2227
#define IDD_CAD_RESULTS_PANE_LARGE      2228
#define IDD_PATIENT_INFO_VERTICAL_LARGE 2229
#define IDC_CAD_VERSION                 2230
#define IDT_PANE_CAD_RESULTS            2231
#define IDC_DIVIDER_1                   2232
#define IDC_DIVIDER_2                   2233
#define IDC_SPEED_TEXT                  2234
#define IDT_UDSEGMENTS_MAUI             2235
#define IDD_CONTROLS_HORIZONTAL_WIDESCREEN 2236
#define IDT_STANDARDVIEW2               2237
#define IDT_STANDARDVIEW_WIDESCREEN_DASHBOARD 2238
#define IDT_STANDARDVIEW_WIDESCREEN     2239
#define IDD_PATIENT_INFO_WIDESCREEN     2240
#define IDT_VERIFICATION_WIDESCREEN     2241
#define IDT_ENDOSLICE_WIDESCREEN        2242
#define IDT_DUALORTHOGONAL_WIDESCREEN   2243
#define IDT_DUALOVERVIEW_WIDESCREEN     2244
#define IDT_SINGLEORTHOGONAL_WIDESCREEN 2245
#define IDT_VERIFICATION_LANDSCAPE      2246
#define IDT_STANDARDVIEW_LANDSCAPE      2247
#define IDT_ENDOSLICE_LANDSCAPE         2248
#define IDT_SINGLEORTHOGONAL_LANDSCAPE  2249
#define IDT_DUALOVERVIEW_LANDSCAPE      2250
#define IDT_DUALORTHOGONAL_LANDSCAPE    2251
#define IDT_REGISTRATION_LANDSCAPE      2252
#define IDT_REGISTRATION_CAD_LANDSCAPE  2253
#define IDC_CDB_TOOL_LIGHTING           2254
#define IDC_CDB_TOOL_TRANSLUCENCY       2255
#define IDC_CDB_TOOL_LINEMEASURE        2256
#define IDC_CDB_TOOL_ANNOTATION         2257
#define IDC_CDB_TOOL_2DROI              2258
#define IDT_STANDARDVIEW_WIDESCREEN_BARTOP 2259
#define IDM_LUNG_NODULE                 3000
#define IDM_LUNG_GRANULOMA              3001
#define IDM_LUNG_PNEUMOTHORAX           3002
#define IDM_LIVER_MASS                  3003
#define IDM_LIVER_CYST                  3004
#define IDM_LIVER_GALLSTONES            3005
#define IDM_LIVER_FATTY                 3006
#define IDM_ADRENAL_MASS                3007
#define IDM_RENAL_MASS                  3008
#define IDM_RENAL_CYST                  3009
#define IDM_RENAL_STONES                3010
#define IDM_RENAL_SCAR                  3011
#define IDM_RENAL_HYDRONEPHROSIS        3012
#define IDM_VASCULAR_AAA                3013
#define IDM_VASCULAR_CALCIFICATION      3014
#define IDM_SPLEEN_MASS                 3015
#define IDM_SPLEEN_GRANULOMA            3016
#define IDM_GI_INGUINAL                 3017
#define IDM_GI_HIATAL                   3018
#define IDM_GYNECOLOGY_FIBROIDS         3019
#define IDM_MISC_OTHER                  3020
#define IDC_RB_SHAPE_ROUND              3021
#define IDC_RB_SHAPE_OVAL               3022
#define IDC_RB_SHAPE_FLAT               3023
#define IDC_RB_LOCATION_SECUM           3024
#define IDC_RB_LOCATION_ASCENDING       3025
#define IDC_RB_LOCATION_HEPATIC         3026
#define IDC_RB_LOCATION_TRANSVERSE      3027
#define IDC_RB_LOCATION_SPLENIC         3028
#define IDC_RB_LOCATION_DESCENDING      3029
#define IDC_RB_LOCATION_SIGMOID         3030
#define IDC_RB_LOCATION_RECTUM          3031
#define IDC_RB_SIZE_NONE                3032
#define IDC_RB_SIZE_INCREASE            3033
#define IDC_RB_SIZE_DECREASE            3034
#define IDC_RB_SIZE_SAME                3035
#define IDC_RB_FEATURES_SIMILAR         3036
#define IDC_RB_FEATURES_GRADUAL         3037
#define IDC_RB_FEATURES_ABRUPT          3038
#define IDC_RB_FEATURES_INTERMEDIATE    3039
#define IDC_OTHER_COMMENTS              3040
#define IDC_RB_LUNG_GRANULOMAS          3042
#define IDC_RB_LUNG_NODULE              3043
#define IDC_RB_LUNG_PNEUMOTHORAX        3044
#define IDC_RB_LIVER_MASS               3045
#define IDC_RB_LIVER_CYST               3046
#define IDC_RB_LIVER_GALLSTONES         3047
#define IDC_RB_LIVER_FATTY              3048
#define IDC_RB_ADRENAL_MASS             3049
#define IDC_RB_RENAL_MASS               3050
#define IDC_RB_RENAL_CYST               3051
#define IDC_RB_FINDING_POLYP            3052
#define IDC_RB_RENAL_STONES             3053
#define IDC_RB_FINDING_DIVERTICULUM     3054
#define IDC_RB_RENAL_SCAR               3055
#define IDC_RB_FINDING_STENOSIS         3056
#define IDC_RB_RENAL_HYDRONEPHROSIS     3057
#define IDC_RB_SPLEEN_MASS              3058
#define IDC_RB_SPLEEN_GRANULOMAS        3059
#define IDC_STATIC_TRANSLUCENCY         3061
#define IDC_STATIC_SHAPE                3062
#define IDC_RB_GI_INGUINAL              3063
#define IDC_RB_RIGHT_UPPER              3064
#define IDC_RB_GI_HIATAL                3065
#define IDC_RB_RIGHT_MIDDLE             3066
#define IDC_RB_VASCULAR_AAA             3067
#define IDC_RB_RIGHT_LOWER              3068
#define IDC_STATIC_SIZE                 3069
#define IDC_RB_VASCULAR_ARTERIAL        3070
#define IDC_RB_LEFT_UPPER               3071
#define IDC_STATIC_SIZE_LABEL1          3072
#define IDC_RB_GYNECOLOGY_FIBROIDS      3073
#define IDC_STATIC_SIZE_LABEL2          3074
#define IDC_RB_OTHER                    3075
#define IDC_RB_LEFT_LOWER               3076
#define IDC_STATIC_SIZE2                3077
#define IDC_RB_RIGHT_LUNG               3079
#define IDC_RB_LEFT_LUNG                3080
#define IDC_RB_LARGE                    3081
#define IDC_RB_MEDIUM                   3082
#define IDC_RB_SMALL                    3083
#define IDC_RB_INFRAENAL                3084
#define IDC_RB_SUPRARENAL               3085
#define IDC_RB_JUXTARENAL               3086
#define IDC_RB_RIGHt                    3088
#define IDC_RB_LEFT                     3089
#define IDC_RB_RIGHT_UPPERPOLE          3090
#define IDC_RB_RIGHT_MIDDLEPOLE         3091
#define IDC_RB_RIGHT_LOWERPOLE          3092
#define IDC_RB_LEFT_UPPERPOLE           3093
#define IDC_RB_SUPERIOR                 3094
#define IDC_RB_LEFT_MIDDLEPOLE          3095
#define IDC_RB_MIDDLE                   3096
#define IDC_RB_LEFT_LOWERPOLE           3097
#define IDC_RB_INFERIOR                 3098
#define IDC_RB_MILD                     3099
#define IDC_RB_MODERATE                 3100
#define IDC_RB_SEVERE                   3101
#define IDC_CB_LUNG_NODULE              3102
#define IDC_CB_LUNG_GRANULOMAS          3103
#define IDC_CB_LUNG_PNEUMOTHORAX        3104
#define IDC_CB_LIVER_MASS               3105
#define IDC_CB_LIVER_CYST               3106
#define IDC_CB_LIVER_GALLSTONES         3107
#define IDC_CB_LIVER_FATTY              3108
#define IDC_CB_ADRENAL_MASS             3109
#define IDC_CB_RENAL_MASS               3110
#define IDC_CB_RENAL_CYST               3111
#define IDC_CB_RENAL_STONES             3112
#define IDC_CB_RENAL_SCAR               3113
#define IDC_CB_RENAL_HYDRONEPHROSIS     3114
#define IDC_CB_SPLEEN_MASS              3115
#define IDC_CB_SPLEEN_GRANULOMAS        3116
#define IDC_CB_GI_INGUINAL              3117
#define IDC_CB_GI_HIATAL                3118
#define IDC_CB_VASCULAR_AAA             3119
#define IDC_CB_VASCULAR_ARTERIAL        3120
#define IDC_CB_GYNECOLOGY_FIBROIDS      3121
#define IDC_CB_OTHER                    3122
#define IDC_INDICATIONS                 3123
#define IDC_RECOMMENDATIONS             3124
#define IDC_INDICATION_OTHER            3125
#define IDC_RECOMMENDATIONS2            3126
#define IDC_YEARS                       3127
#define IDC_BUTTON_LUNG                 3128
#define IDC_BUTTON_LIVER                3129
#define IDC_BUTTON_ADRENAL              3130
#define IDC_BUTTON_RENAL                3131
#define IDC_BUTTON_VASCULAR             3132
#define IDC_BUTTON_SPLEEN               3133
#define IDC_BUTTON_GI                   3134
#define IDC_BUTTON_MISC                 3135
#define IDC_RECOMMEND_OTHER             3136
#define IDC_IMPRESSION                  3137
#define IDC_GROUP_SHAPE                 3138
#define IDC_LIST_LOCATION               3139
#define IDC_GROUP_LOCATION              3140
#define IDC_LIST_SIZE                   3141
#define IDC_LIST_LEVEL                  3142
#define IDC_GROUP_FEATURES              3143
#define IDC_STATIC_LUNG                 3144
#define IDC_GROUP_DRAWING               3145
#define IDC_GROUP_FINDING               3146
#define IDC_STATIC_LIVER                3147
#define IDC_STATIC_ADRENAL              3148
#define IDC_STATIC_RENAL                3149
#define IDC_STATIC_VASCULAR             3150
#define IDC_STATIC_SPLEEN               3151
#define IDC_STATIC_GI                   3152
#define IDC_STATIC_GYNECOLOGY           3153
#define IDC_STATIC_MISC                 3154
#define IDC_PREFS_DEFAULTS_FLIGHTSPEED  3155
#define IDC_PREFS_DEFAULTS_FOV          3156
#define IDC_CDR_SLIDER                  3157
#define IDC_GENERALPAGE_CADDEFAULT_CHECK 3158
#define IDC_RPT_COMBO_CRADSCAT          3159
#define IDC_GENERALPAGE_CADDEFAULT_SLIDER 3160
#define IDC_RPT_OTHER_CRADS_CAT         3161
#define IDC_GENERALPAGE_CADDEFAULT_DISP 3162
#define IDC_CDR_CADUNAVAILABLE          3163
#define IDC_SELSER_FILELIST             3164
#define IDC_TEMPLATE_3DSEGMENTSCROLL    3165
#define IDC_TEMPLATE_ENDOSCOPIC         3166
#define IDC_TEMPLATE_SEGMENTSVIEW       3167
#define IDC_TEMPLATE_3DSEGMENTSVIEW     3168
#define IDC_AJT_PRESETS_COMBO           3169
#define IDC_RCF_FLEXURE_CHECK           3170
#define IDC_RCF_GROUPBOX_ORGAN          3171
#define IDC_RCF_GROUPBOX_FINDINGDESC    3172
#define IDC_RCF_GROUP_ORGAN             3173
#define IDC_RCF_GROUP_FINDINGDESC       3174
#define IDC_RCF_GROUPBOX_COMMENTS       3175
#define IDC_GENERALPAGE_MONITORCOMBO    3176
#define IDC_GENERALPAGE_CHANGEMONITOR   3177
#define IDC_SELSER_FILEINFO             3178
#define IDC_TEMPLATE_MISSED_REGIONS_DLG 3179
#define IDC_GENERALPAGE_DETECTWIDESCREEN 3180
#define IDC_STANDARD_PANE_TABCTRL       3181
#define IDC_VERIFY_LEFTINFO             3182
#define IDC_VERIFY_RIGHTINFO            3183
#define IDC_DATE2                       3184
#define IDC_PHYSICIAN2                  3185
#define IDC_SEX2                        3186
#define IDC_ID2                         3187
#define IDC_NAME2                       3188
#define IDC_AUTHOR2                     3189
#define IDC_AGE2                        3190
#define IDD_ADJUST_TRANSLUCENCY_WIDESCREEN 3191
#define IDT_3DSEGMENTS_WIDESCREEN       3192
#define IDD_RPT_MISC_DUAL               3193
#define IDT_3DSEGMENTS_LANDSCAPE        3194
#define IDD_ADJUST_TRANSLUCENCY_LARGE   3195
#define IDD_ADJUST_TRANSLUCENCY_WIDESMALL 3196
#define IDD_CONTROLS_HORIZONTAL_WIDESMALL 3197
#define IDC_TEMPLATE_PATIENTINFO2       3198
#define IDC_RPTMISC_EXAMQUALITY         3199
#define IDC_RPTMISC_CRADS_VERBOSE       3200
#define IDC_RPTMISC_ERADS_VERBOSE       3201
#define IDC_RPTMISC_CRDAS_LINK_STATIC   3202
#define IDC_RPTMISC_XCRDAS_LINK_STATIC  3203
#define IDT_DUAL_VERIFYORTHOGONAL_WIDESCREEN 3204
#define IDT_MOVIEVIEW_DUAL_WIDESCREEN   3205
#define IDT_MOVIEVIEW_SINGLE_WIDESCREEN 3206
#define IDT_REGISTRATION_WIDESCREEN     3207
#define IDT_REGISTRATION_CAD_WIDESCREEN 3208
#define IDT_FULLOBLIQUE_LANDSCAPE       3209
#define IDT_FULLOBLIQUE_WIDESCREEN      3210
#define IDC_RSP_PANEHDR_MISSEDREGIONS   3211
#define IDC_CONTAINER_GROUPBOX          3212
#define IDT_REGISTRATION_PORTRAITDUMBLOOKING 3213
#define IDT_VERIFICATION_PORTRAIT_LARGE 3214
#define IDT_SINGLEORTHOGONAL_PORTRAIT_LARGE 3215
#define IDT_STANDARDVIEW_PORTRAIT_LARGE 3216
#define IDT_ENDOSLICE_PORTRAIT_LARGE    3217
#define IDT_3DSEGMENTS_PORTRAIT_LARGE   3218
#define IDT_REGISTRATION_PORTRAIT_LARGE 3219
#define IDT_REGISTRATION_CAD_PORTRAIT_LARGE 3220
#define IDT_DUALORTHOGONAL_PORTRAIT_LARGE 3221
#define IDD_PATIENT_INFO_HORIZONTAL_SMALL 3222
#define IDT_MOVIEVIEW_DUAL_PORTRAIT_LARGE 3223
#define IDT_MOVIEVIEW_SINGLE_PORTRAIT_LARGE 3224
#define IDT_MOVIEVIEW_SINGLE_PORTRAIT_LARGE1 3225
#define IDT_MOVIEVIEW_SINGLE_PORTRAIT   3226
#define IDT_MOVIEVIEW_DUAL_PORTRAIT     3227
#define IDC_VSP_CLOSE                   3228
#define IDC_PREFS_DEFAULTS_RESET        3229
#define IDC_PREFS_DEFAULTS_LAYOUT_LABEL 3230
#define IDC_PREFS_DEFAULTS_LAYOUT       3231
#define IDC_PREFS_DEFAULTS_FLIGHTSPEED_LABEL 3232
#define IDC_PREFS_DEFAULTS_FLIGHT_SPEED_LABEL 3233
#define IDC_PREFS_DEFAULTS_MOUSE_COORDS_LABEL 3234
#define IDC_PREFS_DEFAULTS_QUICK_ANNOTATION_LABEL 3235
#define IDC_PREFS_DEFAULTS_SCROLLBAR_ORIENTATION_LABEL 3236
#define IDC_PREFS_DEFAULTS_DISPLAY_EC_CAD_LABEL 3237
#define IDC_PREFS_DEFAULTS_DISPLAY_CLEANSED_LABEL 3238
#define IDC_PREFS_DEFAULTS_2D_MEASUREMENT_PROFILE_LABEL 3239
#define IDC_PREFS_DEFAULTS_COLOR_SCHEME_LABEL 3240
#define IDC_PREFS_DEFAULTS_PSUEDO_COLOR_LABEL 3241
#define IDC_PREFS_DEFAULTS_VOLUME_MEASURE_LABEL 3242
#define IDC_PREFS_DEFAULTS_LINK_DATASETS_LABEL 3243
#define IDC_PREFS_DEFAULTS_DISPLAY_CENTERLINE_LABEL 3244
#define IDC_PREFS_DEFAULTS_MOUSE_COORDS 3245
#define IDC_PREFS_DEFAULTS_QUICK_ANNOTATION 3246
#define IDC_PREFS_DEFAULTS_SCROLLBAR_ORIENTATION 3247
#define IDC_PREFS_DEFAULTS_FOV_LABEL    3248
#define IDC_PREFS_DEFAULTS_DISPLAY_EC_CAD 3249
#define IDC_PREFS_DEFAULTS_DISPLAY_CLEANSED 3250
#define IDC_PREFS_DEFAULTS_2D_MEASUREMENT_PROFILE 3251
#define IDC_PREFS_DEFAULTS_COLOR_SCHEME 3252
#define IDC_PREFS_DEFAULTS_PSUEDO_COLOR 3253
#define IDC_PREFS_DEFAULTS_VOLUME_MEASURE 3254
#define IDC_PREFS_DEFAULTS_LINK_DATASETS 3255
#define IDC_PREFS_DEFAULTS_DISPLAY_CENTERLINE 3256
#define IDC_PREFS_DEFAULTS_APPLY_NOW    3257
#define IDC_PREFS_DEFAULTS_TOOLBAR_POSITION_LABEL  3257
#define IDC_PREFS_DEFAULTS_GENERAL_LABEL 3258
#define IDC_PREFS_DEFAULTS_DISPLAY_LABEL 3259
#define IDC_PREFS_DEFAULTS_LAYOUT_APPLY_NOW 3260
#define IDC_PREFS_DEFAULTS_FOV_DISPLAY  3261
#define IDC_PREFS_DEFAULTS_WARNING      3262
#define IDP_PREFS_DEFAULTS              3263
#define IDC_PREFS_DEFAULTS_TOOLBAR_POSITION 3263
#define IDC_PREFS_DEFAULTS_2D_MEASUREMENT_PROFILE2 3263
#define IDC_CDR_SLIDER1                 3264
#define IDT_ENDOSLICE_WIDESCREEN_BARTOP 3265
#define IDT_DUALORTHOGONAL_WIDESCREEN_BARTOP 3266
#define IDT_3DSEGMENTS_WIDESCREEN_BARTOP 3267
#define IDD_CONTROLS_VERTICAL_PORTRAIT  3268
#define IDD_CONTROLS_VERTICAL_LARGE_PORTRAIT 3269
#define IDC_PROGRESS1                   3277
#define IDC_PROGRESS                    3277
#define IDC_PROGRESS_LABEL              3278
#define IDM_STUDY_OPEN                  32771
#define ID_HELP_CONTENTS                32772
#define ID_HELP_TUTORIAL                32773
#define IDM_STUDY_CLOSE                 32774
#define IDM_REPORT_ADDSNAPSHOT          32775
#define IDM_BOOKMARKS_ADDBOOKMARK       32776
#define IDM_BOOKMARKS_BOOKMARK_LIST     32777
#define IDM_PROGRAM_PREFERENCES         32778
#define IDM_VIEWWINDOW_MAINWINDOW       32779
#define IDT_ENDOSCOPIC_VIEW             32780
#define IDT_SLICE_VIEW_SAGITTAL         32781
#define IDT_SLICE_VIEW_CORONAL          32782
#define IDT_SLICE_VIEW_TRANSVERSE       32783
#define ID_OVERVIEW_SLICEINDICATORS_AXIAL 32784
#define ID_OVERVIEW_SLICEINDICATORS_SAGITTAL 32785
#define ID_OVERVIEW_SLICEINDICATORS_CORONAL 32786
#define ID_OVERVIEW_SLICEINDICATORS_CROSSSECTIONAL 32787
#define ID_OVERVIEW_RESETDISPLAY        32788
#define ID_OVERVIEW_OPTIONS_CENTERLINE  32789
#define ID_OVERVIEW_OPTIONS_TRANSPARENT 32790
#define ID_OVERVIEW_OPTIONS_FRAMEBOX    32791
#define ID_ENDOSCOPICVIEW_SLICEINDICATORS_AXIAL 32792
#define ID_ENDOSCOPICVIEW_SLICEINDICATORS_SAGITTAL 32793
#define ID_ENDOSCOPICVIEW_SLICEINDICATORS_CORONAL 32794
#define ID_ENDOSCOPICVIEW_SLICEINDICATORS_CROSSSECTIONAL 32795
#define ID_ENDOSCOPICVIEW_OPTIONS_CENTERLINE 32796
#define ID_ENDOSCOPICVIEW_OPTIONS_MARKING 32797
#define ID_ENDOSCOPICVIEW_OPTIONS_TRANSLUCENT_DISPLAY 32798
#define ID_ENDOSCOPICVIEW_CURRENTMODE_LINEMEASURE 32799
#define ID_ENDOSCOPICVIEW_CURRENTMODE_LIGHTING 32800
#define ID_ENDOSCOPICVIEW_CURRENTMODE_AUTOFLY 32801
#define ID_ENDOSCOPICVIEW_NAVIGATIONHEADING_TORECTUM 32802
#define ID_ENDOSCOPICVIEW_NAVIGATIONHEADING_TOCECUM 32803
#define ID_ENDOSCOPICVIEW_FLIPVIEWDIRECTION 32804
#define ID_ORTHOGONALVIEW_RESETWL       32805
#define ID_ORTHOGONALVIEW_WLPRESET_COLON 32806
#define ID_ORTHOGONALVIEW_WLPRESET_LUNG 32807
#define ID_ORTHOGONALVIEW_WLPRESET_HEART 32808
#define ID_OVERVIEW_NEXTSEGMENT         32809
#define ID_OVERVIEW_PREVSEGMENT         32810
#define ID_ORTHOGONALVIEW_MEASUREMENT   32811
#define ID_ORTHOGONALVIEW_WLPRESET_EDITPRESETS 32812
#define ID_WINDOWLEVEL_ABDOMEN          32813
#define ID_WINDOWLEVEL_LUNG             32814
#define ID_WINDOWLEVEL_BONE             32815
#define ID_WINDOWLEVEL_LIVER            32816
#define ID_BOOKMARKS_LEVEL_HIGH         32817
#define ID_BOOKMARKS_LEVEL_MEDIUM       32818
#define ID_BOOKMARKS_LEVEL_LOW          32819
#define ID_BOOKMARKS_DELETE             32820
#define ID_BOOKMARKS_GOTO               32821
#define ID_REPORT_GENERATEREPORT        32822
#define ID_REPORTENTRY_GOTOENTRY        32823
#define ID_REPORTENTRY_DELETE           32824
#define IDM_HELP                        32825
#define IDM_TOGGLE_AUTOFLY              32826
#define IDM_JUMP_PREVSEGMENT            32827
#define IDM_JUMP_NEXTSEGMENT            32828
#define IDM_SHOW_NEXT_VIEW              32829
#define ID_VIEWWINDOW_SHOWPOSITION      32830
#define IDM_NEXT_MISSED_REGION          32831
#define IDM_TOGGLE_VIEW_DIRECTION       32832
#define IDM_CANCEL_LOAD                 32833
#define ID_SLICEORIENTATION_AXIAL       32834
#define ID_SLICEORIENTATION_SAGITTAL    32835
#define ID_SLICEORIENTATION_CORONAL     32836
#define ID_SLICEORIENTATION_CROSSSECTIONAL 32837
#define ID_SLICEORIENTATION_VIEWDIRECTION 32838
#define IDM_USERS                       32839
#define IDM_USR_LOGOUT                  32840
#define IDM_USR_PASSCHANGE              32841
#define ID_SLICEZOOM_100                32842
#define IDM_RPT_COLON_FINDINGS          32843
#define IDM_RPT_OTHER_FINDINGS          32844
#define IDM_OPEN_REPORT                 32845
#define IDM_RPT_NON_DISTENDED           32846
#define IDM_RPT_RECOMMENDATIONS         32847
#define IDM_RPT_PREVIEW                 32848
#define ID_WINDOWLEVEL_RESET            32849
#define IDM_RPT_DELETE_ENTRY            32850
#define IDM_RPT_DELETE_IMAGE            32851
#define IDM_RPT_JUMP                    32852
#define IDM_RPT_MISCELLANEOUS           32853
#define IDM_RPT_SAVE                    32854
#define IDM_RPT_DELETE_NONDISTENDED     32855
#define IDM_RPT_RELOAD_NONDISTENDED     32856
#define ID_VIEWWINDOW_JUMPTOVIEWPOSITION 32857
#define ID_VIEWWINDOW_PSEUDOCOLORDISPLAY 32858
#define ID_ENDOSCOPICVIEW_CURRENTMODE_ROIMEASURE 32859
#define IDS_CDRW_ANONYMIZING            32860
#define IDM_TOGGLE_SUPINE_PRONE         32861
#define IDM_RPT_DELETE_ALL_NONDISTENDED 32862
#define IDM_RPT_DELETE_ALL_FINDINGS     32863
#define ID_OVERVIEW_OPTIONS_BOOKMARK    32864
#define ID_PLACEHOLDER_PREVIEW          32865
#define IDM_OPTIONS_SHOWDELETEDSTUDIES  32866
#define ID_STUDYBROWSERITEM_OPENSTUDY   32867
#define ID_STUDYBROWSERITEM_TRANSFER    32868
#define ID_STUDYBROWSERITEM_OPENREPORT  32869
#define ID_STUDYBROWSERITEM_DELETE      32870
#define ID_STUDYBROWSERITEM_STUDYINFO   32871
#define ID_VIEWWINDOW_LINEMEASUREMENT   32872
#define ID_VIEWWINDOW_ROIMEASUREMENT    32873
#define ID_VIEWWINDOW_SNAPSHOT          32874
#define ID_STUDY_OPTIONS_SHOWORTHOGONALHISTOGRAM 32875
#define IDM_OPTIONS_SHOWMEASUREMENTPROFILES 32876
#define IDM_SOPEN_V1K                   32877
#define IDM_SOPEN_V2K                   32878
#define IDM_SOPEN_CD                    32879
#define IDM_SOPEN_PACS                  32880
#define IDM_SOPEN_FILE                  32881
#define ID_VIEWWINDOW_SHOWCLEANSED      32882
#define ID_VIEWWINDOW_UPDATEENDOLUMINALVIEW 32884
#define ID_VIEWWINDOW_ARROWINSLICECENTER 32885
#define IDC_DBS_OPENMOVIE               32886
#define IDM_RPT_NONDISTENDED_UNCERTAIN  32887
#define IDM_RPT_DISTANCE_UNCERTAIN      32888
#define ID_VIEWWINDOW_SWITCHFLIGHTDIRECTION 32889
#define ID_VIEWWINDOW_FLIGHTOPTIONS_SWITCHFLIGHTDIRECTION 32890
#define IDM_OPTIONS_COLORSCHEME_1       32891
#define IDM_OPTIONS_COLORSCHEME_2       32892
#define ID_REPORT_MARKCOMPLETE          32893
#define ID_WINDOWLEVEL_ABDOMEN2         32894
#define ID_STUDYBROWSERITEM_OPENCONTAININGFOLDER 32895
#define ID_OPTIONS_DISPLAYRENDERSPEED   32896
#define ID_OVERVIEW_REGISTRATION_ALLFEATURES 32897
#define ID_OVERVIEW_REGISTRATION_MATCHEDFEATURES 32898
#define ID_OVERVIEW_REGISTRATIONOPTIONS_SHOWMATCHEDFEATURES 32899
#define ID_OVERVIEW_REGISTRATIONOPTIONS_ALLFEATURES 32900
#define ID_OVERVIEW_REGISTRATIONOPTIONS_MATCHEDFEATURES 32901
#define ID_OVERVIEW_REGISTRATIONOPTIONS_FEATUREINFO 32902
#define ID_STUDYBROWSERITEM_OPENWITH_EXPLORER 32903
#define IDM_BOOKMARKS_DELETEALLBOOKMARKS 32904
#define IDM_MEASUREMENTS_DELETEALL      32905
#define ID_VIEWWINDOW_MEASUREMENTOPTIONS_ADDANNOTATION 32906
#define IDM_NOTATIONS_ANNOTATIONS_DELETEALLANNOTATIONS 32907
#define IDM_NOTATIONS_ANNOTATION_LIST_FIRST 32908
#define ID_ANNOTATION_EDITTEXT          32909
#define ID_ANNOTATION_DELETE            32910
#define ID_ANNOTATION_GOTO              32911
#define ID_ANNOTATION_SHOWTEXT          32912
#define ID_USERREGISTRATION_DELETE      32913
#define ID_USERREGISTRATION_CLEARALLUSERFEATURES 32914
#define ID_OVERVIEW_DISPLAYOPTIONS_MARKING 32915
#define IDM_RPT_DELETE_ALL_ENTRIES      32916
#define IDS_PEDUNCULATED_STALK_SEEN     32917
#define IDS_PEDUNCULATED_STALK_UNSEEN   32918
#define ID_OPTIONS_ADJUSTTRANSLUCENCY   32919
#define ID_VIEWWINDOW_2DSLICE           32920
#define ID_VIEWWINDOW_MIP               32921
#define ID_VIEWWINDOW_THINSLAB          32922
#define ID_ENDOSCOPICVIEW_CURRENTMODE_SEGMENTREGION 32923
#define IDM_RPT_JUMPTOFINDINGVIEW       32925
#define ID_OPTIONS_CONTROLPAD_FLIGHTCONTROLS 32926
#define ID_OPTIONS_CONTROLPAD_ADJUSTTRANSLUCENCY 32927
#define ID_VIEWWINDOW_SHOWWORLDCOORDINATES 32928
#define ID_VIEWWINDOW_SHOWVOLUMECOORDINATES 32929
#define ID_SHOWCAD_UNDECIDED            32930
#define ID_SHOWCAD_SHOW                 32931
#define ID_SHOWCAD_HIDE                 32932
#define ID_OPTIONS_ALWAYSSHOWCADINDICATORS 32933
#define ID_CADOPTIONS_SHOWEXTRACOLONIC  32934
#define ID_SET_PRIMARY_VOLUME           32935
#define ID_SET_PRIMARY_PREPROCESSED     32936
#define ID_SET_PRIMARY_CAD              32937
#define ID_SET_SECONDARY_VOLUME         32938
#define ID_SET_SECONDARY_PREPROCESSED   32939
#define ID_SET_SECONDARY_CAD            32940
#define ID_SET_SESSION_SERIES           32941
#define ID_SET_BROWSE_LOCATION          32942
#define ID_SET_ALL                      32943
#define ID_OPTIONS_SRTOPTIONS           32944
#define ID_SRTOPTIONS_DISPLAYREGIONSOFINTEREST 32945
#define IDM_SRTOPTIONS_DISPLAYREGIONSOFINTEREST 32946
#define IDM_VIEWWINDOW_FULLSCREEN       32947
#define ID_WINDOWLEVEL_SAVENEW          32948
#define ID_WINDOWLEVEL_DELETESELECTED   32949
#define ID_WINDOWLEVEL_CUSTOM           32950
#define IDM_2DANNOTATIONS_EDITQUICKDROPNAME 32951
#define ID_2DDISPLAYOPTIONS_VERTICALSCROLLBARS 32952
#define ID_REGIONEDITINGTOOLS_REGIONNEW 32953
#define ID_REGIONEDITINGTOOLS_REGIONREMOVE 32954
#define ID_REGIONEDITINGTOOLS_VOXELADD  32955
#define ID_REGIONEDITINGTOOLS_VOXELDELETE 32956
#define IDM_NOTATIONS_3DMEASUREMENTS_LIST_FIRST 32957
#define ID_SLICEVIEW_MEASUREMENTTOOLS_VOLUMEMEASUREMENT 32958
#define ID_OVERVIEW_SLICEINDICATORS_DISSECTION 32959
#define ID_OPTIONS_CONTROLPAD_MISSEDREGIONS 32960
#define ID_OPTIONS_CONTROLPAD_CADRESULTS 32961
#define ID_SLICE_CHILD_FORCE_REDRAW     32962
#define IDS_SAVE_SESSION_CLOSE_VIEWER   57608
#define IDS_CLOSE_VIEWER                57608
#define IDS_INDICATOR_STEP              61300
#define IDS_INDICATOR_FUNCTION          61301
#define IDS_INDICATOR_DATETIME          61302
#define IDS_INDICATOR_CAPSLOCK          61303
#define IDS_PICK_SEGMENT_FORMAT         61304
#define IDS_PICK_FINISH                 61305
#define IDS_ROTATE_VIEW                 61306
#define IDS_ZOOM_VIEW                   61307
#define IDS_MOVE_VIEW                   61308
#define IDS_FLIGHT_FORWARD              61309
#define IDS_SPIN_REWIND                 61310
#define IDS_FLIGHT_REVERSE              61311
#define IDS_WINDOWLEVEL                 61312
#define IDS_SCROLL_SLICE                61313
#define IDS_POPUP_MENU                  61314
#define IDS_SEGMENT_LENGTH_WARNING      61315
#define IDS_SELECT                      61316
#define IDS_CUSTOM                      61317
#define IDS_ALIGN_CROSS_SECTIONAL       61318
#define IDS_LUMEN_COVERAGE              61319
#define IDS_PAN_VIEW                    61320
#define IDS_PAN_REWIND                  61321
#define IDS_MEASURE                     61322
#define IDS_MEASURE_DELETE              61323
#define IDS_MEASUREMENT_LIST            61324
#define IDS_MOVE_VIEW_DIRECTION         61325
#define IDS_DETECTING_MISSED_REGIONS    61326
#define IDS_MOVELIGHTSOURCE             61327
#define IDS_MOVEBIOPSY                  61328
#define IDS_VVS_TEST_VERSION            61329
#define IDS_NON_PHYSICIAN_USER          61330
#define IDS_CONTACT_SERVICE             61331
#define IDS_ABOUT_APP_FORMAT            61332
#define IDS_ANNOTATIONS_LIST            61333
#define IDS_ANNOTATION                  61334
#define IDS_ANNOTATION_TEXT_PROMPT      61335
#define IDS_EMPTY_LIST                  61336
#define IDS_LUMEN_COVERAGE_VALUE_FORMAT 61337
#define IDS_LOGINNAME                   61501
#define IDS_PERMISSIONS                 61502
#define IDS_USER                        61503
#define IDS_ADMINISTRATOR               61504
#define IDS_SERVICE                     61505
#define IDS_FIRST                       61506
#define IDS_NEXT                        61507
#define IDS_VALUE                       61508
#define IDS_PHYSICIANNAME               61509
#define IDS_PHYSICIANPREFIX             61510
#define IDS_PREFS_DLGNAME               61511
#define IDS_DRIVE                       61512
#define IDS_SHARENAME                   61513
#define IDS_PATIENTNAME                 61514
#define IDS_PATIENTID                   61515
#define IDS_PATIENTINFO                 61516
#define IDS_SCANDATE                    61517
#define IDS_REFERRINGPHYSICIAN          61518
#define IDS_FILETYPE                    61519
#define IDS_CONTENT                     61520
#define IDS_FILENAME                    61521
#define IDS_FILESTATUS                  61522
#define IDS_FILELOCATION                61523
#define IDS_LOCATION                    61523
#define IDS_DBDLG_INFOTITLE             61524
#define IDS_INVALID_LOGIN               61525
#define IDS_ERROR_CHANGING_PASSWORD     61526
#define IDS_DELETE                      61527
#define IDS_TRANSFERRING                61528
#define IDS_PASSWORD_MISMATCH           61529
#define IDS_PASSWORD_CHANGE             61530
#define IDS_EXAMSITE                    61531
#define IDS_FIRST_PAGE_NUMBERING_FORMAT 61532
#define IDS_PAGE_NUMBERING_FORMAT       61533
#define IDS_PATIENT                     61534
#define IDS_STUDYDATE                   61535
#define IDS_INTRODUCTION                61536
#define IDS_RELOAD                      61537
#define IDS_SUPINE_ABBREV               61538
#define IDS_PRONE_ABBREV                61539
#define IDS_READ_ABBREV                 61540
#define IDS_CDRW_CREATEIMAGE            61541
#define IDS_CDRW_WRITE                  61542
#define IDS_CDRW_FINALIZING             61543
#define IDS_PHYSICIAN                   61544
#define IDS_UPDATE                      61550
#define IDS_FINISH                      61551
#define IDS_BACK                        61552
#define IDS_PICK_VERIFY_FORMAT          61553
#define IDS_PICK_PRESS_PRONE            61554
#define IDS_PICK_LENGTH_WARNING_FORMAT  61555
#define IDS_THIS                        61556
#define IDS_SEGMENT                     61557
#define IDS_ADD_USER_REGISTRATION       61558
#define IDS_VERIFYTITLE_SEGMENTS        61559
#define IDS_VERIFYTITLE_REGISTRATION    61560
#define IDS_RECEIVED                    61561
#define IDS_CONVERTING                  61562
#define IDS_FAILEDCONVERTING            61563
#define IDS_CONVERTED                   61564
#define IDS_PIPELINING                  61565
#define IDS_FAILEDPIPELINING            61566
#define IDS_COMPLETE                    61567
#define IDS_DELETED                     61568
#define IDS_INCOMPLETE                  61569
#define IDS_INVALID                     61570
#define IDS_LOGOUT_USER_FORMAT          61571
#define IDS_TRANSFER_PROGRESS_FORMAT    61572
#define IDS_TRANSFER_CANCELLING         61573
#define IDS_STUDY_FILES_NOT_FOUND       61574
#define IDS_INSUFFICIENT_DISKSPACE_FORMAT 61575
#define IDS_TRANSFER_STUDY_EXISTS       61576
#define IDS_STUDY_TRANSFER_CLOSE_CURRENT_STUDY 61577
#define IDS_MULTIPLE                    61578
#define IDS_STUDY_TRANSFER_ERROR        61579
#define IDS_DATABASE_UPDATE_ERROR       61580
#define IDS_STUDY_TRANSFER_CD_OVER_CAPACITY 61581
#define IDS_ERROR_STUDYDELETE_FILES     61582
#define IDS_ERROR_STUDYDELETE_DATABASE  61583
#define IDS_ERROR_STUDYDELETE_GENERIC   61584
#define IDS_DATABASE_ERROR_CONNECTIONFAILED 61585
#define IDS_DATABASE_SEARCH_RESULTS_LIST_TITLE_FORMAT 61586
#define IDS_UNREAD_ONLY                 61587
#define IDS_DATABASE_DELETING           61588
#define IDS_DATABASE_SEARCHING          61589
#define IDS_DATABASE_CONNECTING         61590
#define IDS_CONNECTION_TESTING          61591
#define IDS_CONNECTION_TEST_SUCCESS     61592
#define IDS_SELECT_UNAVAILABLE_DATABASE_PROMPT 61593
#define IDS_DATABASE_SELECT_UNAVAILABLE_PROMPT 61593
#define IDS_DATABASE_SEARCH_FILESYSTEM_TOOLTIP 61594
#define IDS_ERROR_STUDYDELETE_CONSTRUCTING 61595
#define IDS_STUDY_TRANSFER_INSERT_DISK_FORMAT 61596
#define IDS_DATABASE_INITIALIZING       61597
#define IDS_APPLICATION_LOADING         61598
#define IDS_STANDARD                    61601
#define IDS_DUALORTHOGONAL              61602
#define IDS_ORTHOGONAL                  61602
#define IDS_ENDOSLICE                   61603
#define IDS_DUAL2D3D                    61604
#define IDS_FULLOBLIQUE                 61605
#define IDS_PATIENTINFORMATION          61800
#define IDS_STUDYLOAD_LOADING_STUDY     61801
#define IDS_STUDYLOAD_HEADER            61802
#define IDS_STUDYLOAD_AXIAL             61803
#define IDS_STUDYLOAD_SAGITTAL          61804
#define IDS_STUDYLOAD_CORONAL           61805
#define IDS_STUDYLOAD_SKELETON          61806
#define IDS_STUDYLOAD_SEGMENTS          61807
#define IDS_STUDYLOAD_THRESHOLD         61808
#define IDS_STUDYLOAD_VOLUME            61809
#define IDS_STUDYLOAD_DFS               61810
#define IDS_STUDYLOAD_DFE               61811
#define IDS_STUDYLOAD_CSI               61812
#define IDS_STUDYLOAD_SLD               61813
#define IDS_STUDYLOAD_INS               61814
#define IDS_STUDYLOAD_SUBMARINE         61815
#define IDS_STUDYLOAD_BOOKMARKS         61816
#define IDS_STUDYLOAD_PAINTING          61817
#define IDS_STUDYLOAD_ERROR_FORMAT      61818
#define IDS_STUDYLOAD_ABORTING          61819
#define IDS_STUDYLOAD_COMPLETING        61820
#define IDS_STUDY_OPEN_FILESYSTEM_FILTER 61821
#define IDS_STUDY_OPEN_FILESYSTEM_TITLE 61822
#define IDS_INCORRECT_FILE_EXTENSION    61823
#define IDS_DISCARD_CHANGES_PROMPT      61824
#define IDS_VERIFY_USER_OPERATION_FORMAT 61825
#define IDS_VERIFY_USER_OPERATION_ALL_FORMAT 61826
#define IDS_OPERATION_SUCCESS_FORMAT    61827
#define IDS_BOOKMARK                    61828
#define IDS_BOOKMARK_LIST               61829
#define IDS_BOOKMARK_NAME_FORMAT        61830
#define IDS_STUDYLOAD_SUPINE            61831
#define IDS_STUDYLOAD_PRONE             61832
#define IDS_SELECT_FROM_LIST_FORMAT     61833
#define IDS_STUDYLOAD_VOLFIELDS         61834
#define IDS_STUDYLOAD_MISMATCHED_REGISTRATION 61835
#define IDS_STUDY_BROWSER               61901
#define IDS_VERIFICATION                61902
#define IDS_NAVIGATION                  61903
#define IDS_REPORT                      61904
#define IDS_STUDY_COMPLETE              61905
#define IDS_STUDY_CLOSING               61906
#define IDS_REGISTRATION                61907
#define IDS_NO_REPORT                   61908
#define IDS_REPORT_READ_ONLY            61909
#define IDS_ENDOSCOPIC                  61911
#define IDS_SLICE                       61912
#define IDS_OVERVIEW                    61913
#define IDS_CHILDVIEW_TITLE_VTXFMT      61914
#define IDS_PRIMARY                     61915
#define IDS_SECONDARY                   61916
#define IDS_ADDUSER_ERR_ILLEGAL_ENTRY   61921
#define IDS_ADDUSER_ERR_DUPLICATE_ENTRY 61922
#define IDS_ADDUSER_ERR_TOOSHORT_ENTRY  61923
#define IDS_ADDUSER_ERR_PASS_VERIFY     61924
#define IDS_ADDUSER_ERR_BADPASS         61925
#define IDS_ADDUSER_ERR_TOOSHORT_PASSWORD 61926
#define IDS_DELUSER_ERR_CURRENT         61927
#define IDS_ULTIMATE_BAD_INTERACTION_USER_IRRITANT 61928
#define IDS_ERROR_GENERIC_FORMAT        61929
#define IDS_STUDY_LOCATIONS_FORMAT      61930
#define IDS_LOCAL                       61951
#define IDS_NETWORK                     61952
#define IDS_COMPACTDISC                 61953
#define IDS_PACS                        61954
#define IDS_FILESYSTEM                  61955
#define IDS_V1000                       61956
#define IDS_V2000                       61957
#define IDS_OTHER                       61958
#define IDS_DIRECTORY                   61959
#define IDS_STUDY                       61960
#define IDS_DATASET                     61961
#define IDS_PREVIEW                     61962
#define IDS_UNMAPPED                    61963
#define IDS_CLOSING_VIEWER_INSTANCE     61964
#define IDS_LOCATION_IN_CM              62001
#define IDS_SIZE_FORMAT                 62002
#define IDS_CM                          62003
#define IDS_MM                          62004
#define IDS_GOTO                        62005
#define IDS_ROI_MAJOR_DIAMETER_FORMAT   62006
#define IDS_ROI_AREA_FORMAT             62007
#define IDS_ROI_AVERAGE_HU_FORMAT       62008
#define IDS_ROI_MAX_HU_FORMAT           62009
#define IDS_ROI_STD_HU_FORMAT           62010
#define IDS_DISTANCE_FROM_RECTUM_FORMAT 62011
#define IDS_LINEMEASUREMENT_FORMAT      62012
#define IDS_DISPLAYING_UNCLEANSED       62013
#define IDS_DISPLAYING_UNCLEANSED_VERBOSE 62014
#define IDS_MAX_DIAMETER                62015
#define IDS_ERROR_UNSPECIFIED           62101
#define IDS_ERROR_MEMORY_EXCEPTION      62102
#define IDS_ERROR_SWITCHVIEW_EXCEPTION  62103
#define IDS_VASCULAR_FINDING_LENGTH_FORMAT 62104
#define IDS_HAZARD001                   62151
#define IDS_HAZARD002                   62152
#define IDS_HAZARD003                   62153
#define IDS_HAZARD004                   62154
#define IDS_HAZARD005                   62155
#define IDS_HAZARD006                   62156
#define IDS_HAZARD007                   62157
#define IDS_HAZARD008                   62158
#define IDS_HAZARD009                   62159
#define IDS_HAZARD010                   62160
#define IDS_HAZARD_CONTINUE             62161
#define IDS_SUPINE_HAZARDS              62162
#define IDS_PRONE_HAZARDS               62163
#define IDS_STUDY_IN_USE_ERROR_FORMAT   62164
#define IDS_DESTINATION_STUDY_IN_USE_ERROR_FORMAT 62165
#define IDS_RPTERR_FORMAT               62200
#define IDS_READ_NONDISTENDED_FINDING   62201
#define IDS_DELETE_COLON_FINDING        62202
#define IDS_READ_COLON_FINDING_ENTRY    62203
#define IDS_ADD_REPORT_IMAGE            62204
#define IDS_MOVE_IMAGE                  62205
#define IDS_RETRIEVE_OTHER_FINDING      62206
#define IDS_ADD_FINDING                 62207
#define IDS_DELETE_FINDING              62208
#define IDS_UPDATE_FINDING              62209
#define IDS_RETRIEVE_FINDING            62210
#define IDS_RETRIEVE_STUDY_INFORMATION  62211
#define IDS_ADD_NONDISTENDED_AREA       62212
#define IDS_DELETE_NONDISTENDED_AREA    62213
#define IDS_ADD_ENTRY                   62214
#define IDS_SAVE                        62215
#define IDS_OPEN                        62216
#define IDS_TRANSFER                    62217
#define IDS_REPORT_OPEN_FILESYSTEM_TITLE 62220
#define IDS_REPORT_OPEN_FILESYSTEM_FILTER 62221
#define IDS_E_LOAD_REPORT               62222
#define IDS_REPORT_SNAPSHOT_ADDED       62223
#define IDS_BOOKMARK_ADDED              62224
#define IDS_ERROR_CREATE_REPORT_PREVIEW 62225
#define IDS_REPORT_NOTGENERATED         62301
#define IDS_MARK                        62302
#define IDS_REMOVE_MARK                 62303
#define IDS_STUDY_AS_COMPLETED          62304
#define IDS_ERROR_3DMODEL_INCOMPLETE    62305
#define IDS_DELETE_CURRENT_STUDY_PROMPT 62306
#define IDS_ERROR_REPORT_READONLY       62307
#define IDS_ERROR_NO_REPORT_OPEN        62308
#define IDS_INDETERMINATE               62401
#define IDS_SIMILAR_TO_COLON_WALL       62402
#define IDS_POLYP                       62403
#define IDS_DIVERTICULUM                62404
#define IDS_STENOSIS                    62405
#define IDS_ROUND                       62406
#define IDS_OVAL                        62407
#define IDS_DENSITY_CHANGE_FORMAT       62408
#define IDS_SESSILE                     62409
#define IDS_GRADUAL                     62410
#define IDS_ABRUPT                      62411
#define IDS_INTERMEDIATE                62412
#define IDS_IMAGE                       62413
#define IDS_FINDING                     62414
#define IDS_MOVE                        62415
#define IDS_CECUM                       62416
#define IDS_RECTUM                      62417
#define IDS_ASCENDING                   62418
#define IDS_ASCENDING_COLON             62419
#define IDS_HEPATIC_FLEXURE             62420
#define IDS_TRANSVERSE                  62421
#define IDS_TRANSVERSE_COLON            62422
#define IDS_SPLENIC_FLEXURE             62423
#define IDS_DESCENDING                  62424
#define IDS_DESCENDING_COLON            62425
#define IDS_SIGMOID                     62426
#define IDS_COLON_FINDINGS              62427
#define IDS_NON_DISTENDED_AREAS         62428
#define IDS_OTHER_FINDINGS              62429
#define IDS_MISCELLANEOUS               62430
#define IDS_SCREENING                   62431
#define IDS_PERSONAL_HISTORY_OF_POLYPS  62432
#define IDS_CONSTIPATION                62433
#define IDS_PERSONAL_HISTORY_OF_CANCER  62434
#define IDS_FAMILY_HISTORY_OF_CANCER    62435
#define IDS_ANEMIA                      62436
#define IDS_HEMATOCHEZIA                62437
#define IDS_ABNORMAL_IMAGING            62438
#define IDS_ABDOMINAL_PAIN              62439
#define IDS_IBD                         62440
#define IDS_DIARRHEA                    62441
#define IDS_POLYP_ON_FLEX_SIGMOID       62442
#define IDS_LUNG_NODULE                 62443
#define IDS_LUNG_GRANULOMA              62444
#define IDS_PNEUMOTHORAX                62445
#define IDS_LIVER_MASS                  62446
#define IDS_LIVER_CYST                  62447
#define IDS_GALLSTONES                  62448
#define IDS_FATTY_LIVER                 62449
#define IDS_ADRENAL_MASS                62450
#define IDS_RENAL_MASS                  62451
#define IDS_RENAL_CYST                  62452
#define IDS_RENAL_STONES                62453
#define IDS_RENAL_SCAR                  62454
#define IDS_HYDRONEPHROSIS              62455
#define IDS_AAA                         62456
#define IDS_ARTERAL_CALCIFICATION       62457
#define IDS_SPLENIC_MASS                62458
#define IDS_SPLENIC_GRANULOMA           62459
#define IDS_INGUINAL_HERNIA             62460
#define IDS_HIATAL_HERNIA               62461
#define IDS_UTERINE_FIBROIDS            62462
#define IDS_RIGHT_UPPER_LOBE            62463
#define IDS_RIGHT_MIDDLE_LOBE           62464
#define IDS_RIGHT_LOWER_LOBE            62465
#define IDS_LEFT_UPPER_LOBE             62466
#define IDS_LEFT_MIDDLE_LOBE            62467
#define IDS_LEFT_LOWER_LOBE             62468
#define IDS_RIGHT_LUNG                  62469
#define IDS_LEFT_LUNG                   62470
#define IDS_RIGHT_LOBE_ANTERIOR_SEGMENT 62471
#define IDS_RIGHT_LOBE_POSTERIOR_SEGMENT 62472
#define IDS_LEFT_LOBE_MEDIAL_SEGMENT    62473
#define IDS_LEFT_LOBE_LATERAL_SEGMENT   62474
#define IDS_RIGHT_LOBE_ANTERIOR         62475
#define IDS_RIGHT_LOBE_POSTERIOR        62476
#define IDS_LEFT_LOBE_MEDIAL            62477
#define IDS_LEFT_LOBE_LATERAL           62478
#define IDS_RIGHT_KIDNEY                62479
#define IDS_LEFT_KIDNEY                 62480
#define IDS_RIGHT_UPPER_POLE            62481
#define IDS_RIGHT_MIDDLE                62482
#define IDS_RIGHT_LOWER_POLE            62483
#define IDS_LEFT_UPPER_POLE             62484
#define IDS_LEFT_MIDDLE                 62485
#define IDS_LEFT_LOWER_POLE             62486
#define IDS_SUPRARENAL                  62487
#define IDS_JUXTARENAL                  62488
#define IDS_INFRARENAL                  62489
#define IDS_MALE                        62490
#define IDS_FEMALE                      62491
#define IDS_OPTICAL                     62492
#define IDS_VIRTUAL                     62493
#define IDS_MONTH                       62494
#define IDS_YEAR                        62495
#define IDS_RIGHT                       62496
#define IDS_LEFT                        62497
#define IDS_SMALL                       62498
#define IDS_MEDIUM                      62499
#define IDS_LARGE                       62500
#define IDS_MILD                        62501
#define IDS_MODERATE                    62502
#define IDS_SEVERE                      62503
#define IDS_SUPERIOR                    62504
#define IDS_MIDDLE                      62505
#define IDS_INFERIOR                    62506
#define IDS_RECOMMENDATIONS             62507
#define IDS_PERSONAL_HISTORY_OF_COLONCANCER 62508
#define IDS_VIRTUAL_COLONOSCOPY_IN      62509
#define IDS_OPTICAL_COLONOSCOPY_IN      62510
#define IDS_OTHER_INDICATIONS_LABEL_FULL 62511
#define IDS_OTHER_INDICATIONS_LABEL_ABBREV 62512
#define IDS_SAVING_MOVIE                62513
#define IDS_OTHER_LOCATION              62514
#define IDS_ALL                         62515
#define IDS_BOTH                        62516
#define IDS_MOVIE                       62517
#define IDS_EXTRA_COLONIC_FINDING       62518
#define IDS_EXTRA_COLONIC_FINDINGS      62518
#define IDS_COLONFINDING_AREA_UNCERTAIN 62519
#define IDS_COLONFINDING_DISTANCE_UNCERTAIN 62520
#define IDS_ANNOTATIONS                 62521
#define IDS_DISTANCE_FROM_RECTUM_UNCERTAIN 62522
#define IDS_COLONFINDING_MISCELLANEOUS_OTHER_FORMAT 62523
#define IDS_EXTRA_COLONIC_FINDING_FORMAT 62524
#define IDS_REPORT_FOOTER_PATIENTDATA_FORMAT 62525
#define IDS_FINDINGS                    62526
#define IDS_INDICATION_ELECTIVE_COLONSCOPY_FORMAT 62601
#define IDS_INDICATION_GENERAL_FORMAT   62602
#define IDS_COLONFINDING_NOTRANSLUCENCY_FORMAT 62603
#define IDS_COLONFINDING_TRANSLUCENCY_FORMAT 62604
#define IDS_COLONFINDING_OTHER_FORMAT   62605
#define IDS_NONDISTENDEDAREAS_HEADING   62606
#define IDS_OTHER_FINDINGS_ENTRY_FORMAT 62607
#define IDS_OTHER_FINDINGS_VASCULARAAA_ENTRY_FORMAT 62608
#define IDS_OTHER_FINDINGS_RECOMMENDATIONS_FOLLOWUP_FORMAT 62609
#define IDS_OTHER_FINDINGS_RECOMMENDATIONS_POLYP_REMOVAL 62610
#define IDS_SCHEDULE_FOR_POLYP_REMOVAL  62611
#define IDS_RPT_NORMAL                  62612
#define IDS_NORMAL_FINDING_FORMAT       62613
#define IDS_HEADER_PROMPT               62614
#define IDS_E_HEADER                    62615
#define IDS_IMPRESSION                  62616
#define IDS_IMAGE_TRANSFER_SUCCESSFUL   62617
#define IDS_ERROR_CREATING_REPORT       62618
#define IDS_GENERATING_REPORT           62619
#define IDS_REPORT_PDF_FILENAME         62620
#define IDS_MOVIE_STATS_FORMAT          62621
#define IDS_OTHER_LOCATION_FORMAT       62631
#define IDS_STUDY_DESCR_FORMAT          62640
#define IDS_STUDYTYPE_COLON             62641
#define IDS_STUDYTYPE_CALCIUM           62642
#define IDS_STUDYTYPE_AAA               62643
#define IDS_STUDYTYPE_EXPLORER          62644
#define IDS_STUDYTYPE_UNKNOWN           62645
#define IDS_STUDYABBREV_COLON           62651
#define IDS_STUDYABBREV_CALCIUM         62652
#define IDS_STUDYABBREV_AAA             62653
#define IDS_STUDYABBREV_EXPLORER        62654
#define IDS_SUPINE                      62701
#define IDS_PRONE                       62702
#define IDS_SCOUT                       62703
#define IDS_NON_CONTRAST                62704
#define IDS_IMMEDIATE_CONTRAST          62705
#define IDS_DELAYED_CONTRAST            62706
#define IDS_CALCIUM_PROSPECTIVE         62707
#define IDS_PROSPECTIVE                 62707
#define IDS_SUPINE_EXTRA                62708
#define IDS_PRONE_EXTRA                 62709
#define IDS_FAMILY_HISTORY_OF_POLYPS    62710
#define IDS_RETROSPECTIVE               62711
#define IDS_CYLINDRICAL_SEGMENTS        62712
#define IDS_MEDIADISK_AUTORUNINF_FORMAT 62801
#define IDS_V3DEXE_CONSOLE              63001
#define IDS_V3DEXE_COLON                63002
#define IDS_V3DEXE_DELETER              63003
#define IDS_V3DEXE_MEDIAPLAY            63004
#define IDS_V3DEXE_LAUNCH_ERROR_FORMAT  63005
#define IDS_ERROR_INSUFFICIENT_RESOURCES_FOR_STUDY 63006
#define IDS_PROMPT_LOAD_LARGE_STUDY     63007
#define IDS_HELP_FACILITY               63008
#define IDS_V3DEXE_DEADLOCKED_FORMAT    63009
#define IDS_COMMENTS                    63010
#define IDS_2DSEGMENTS                  63011
#define IDS_3DSEGMENTS                  63012
#define IDS_CHECKING_V3DPROCESSOR_ACTIVITY 63013
#define IDS_OPEN_WHILE_PROCESSING_PROMPT 63014
#define IDS_OK                          63101
#define IDS_CANCEL                      63102
#define IDS_DISCLAIMER                  63103
#define IDS_LUNG                        63201
#define IDS_LIVER                       63202
#define IDS_RENAL                       63203
#define IDS_ADRENAL                     63204
#define IDS_SPLEEN                      63205
#define IDS_GI                          63206
#define IDS_GYNECOLOGY                  63207
#define IDS_VASCULAR                    63208
#define IDS_LUMEN_COVERAGE_WARNING_FORMAT 63209
#define IDS_FINDING_DISTANCE_DEPENDS_ON_SEGMENTS 63210
#define IDS_ADJUST_THICKNESS            63211
#define IDS_SLAB                        63212
#define IDS_MIP                         63213
#define IDS_ANAL_VERGE                  63214
#define IDS_FINDING_LOC_UNKNOWN         63215
#define IDS_PRECONTRAST                 63216
#define IDS_POSTCONTRAST                63217
#define IDS_SHOWSUBTRACTED              63218
#define IDS_SW_LICENSE_REQUESTFAILED    63219
#define IDS_SW_LICENSE_REQUESTNEWPROMPT 63220
#define IDS_ELEC_CLEANSING              63221
#define IDS_REQUESTING_LICENSE          63222
#define IDS_SUBTRACTED                  63223
#define IDS_DISPLAYING_UNSUBTRACTED     63224
#define IDS_DISPLAYING_UNSUBTRACTED_VERBOSE 63225
#define IDS_CADFINDINGS_STATS_DUAL      63226
#define IDS_SHOW                        63227
#define IDS_CADFINDINGS_STATS_SINGLE    63228
#define IDS_CAD_RESULTS                 63229
#define IDS_DELETEMEASUREMENTS_ALLDATASETS 63230
#define IDS_CAD_VERSION                 63230
#define IDS_BOTHDATASETS_DELETEALL_FORMAT 63231
#define IDS_CADFINDINGS_SPHERICITY_STATS 63232
#define IDS_DECUBITUS                   63233
#define IDS_DECUBITUS_L                 63234
#define IDS_DECUBITUS_R                 63235
#define IDS_DECUB                       63236
#define IDS_DECUB_L                     63237
#define IDS_DECUB_R                     63238
#define IDS_POSTCONT                    63239
#define IDS_PRECONT                     63240
#define IDS_SYNCHRONIZE                 63241
#define IDS_REGIONSEGMENT_NONEFOUND     63242
#define IDS_REGIONSEGMENT_SMALLREGION   63243
#define IDS_REGIONSEGMENT_ERROROCCURRED 63244
#define IDS_NOT_LOADED                  63245
#define IDS_ROI_VOLUME_TXT              63246
#define IDS_UDSEGMENTS_MAUI             63247
#define IDS_PEDUNCULATED                63248
#define IDS_FLAT                        63249
#define IDS_FAILED_COLONOSCOPY          63250
#define IDS_NEAR_FLEXURE                63251
#define IDS_PLANE_ANGLE                 63252
#define IDS_FMT_ALWAYSSHOWCADINDICATORS 63253
#define IDS_FMT_SHOWEXTRACOLONICCAD     63254
#define IDS_EXTRA_COLONIC_CRADS         63255
#define IDS_CRADS_OUTPUT                63256
#define IDS_ENTERNEWSETTINGSNAME        63257
#define IDS_MEASURE_DISCLAIMER_FMT      63258
#define IDS_STOOL                       63259
#define IDS_ROITOOL                     63260
#define IDS_QUICKDROP_PROMPT            63261
#define IDS_REPORT_DRAG_IMAGE_PROMPT    63262
#define IDS_REPORT_DRAG_LAST_IMAGE_PROMPT 63263
#define IDS_HIGH_SEDATION_RISK          63264
#define IDS_3DCT                        63265
#define IDS_CRADS_VERBOSE_C0            63266
#define IDS_CRADS_VERBOSE_C1            63267
#define IDS_CRADS_VERBOSE_C2            63268
#define IDS_CRADS_VERBOSE_C3            63269
#define IDS_CRADS_VERBOSE_C4            63270
#define IDS_CRADS_VERBOSE_E0            63271
#define IDS_CRADS_VERBOSE_E1            63272
#define IDS_CRADS_VERBOSE_E2            63273
#define IDS_CRADS_VERBOSE_E3            63274
#define IDS_CRADS_VERBOSE_E4            63275
#define IDS_FECAL_TAGGING               63276
#define IDS_CO2                         63277
#define IDS_ROOMAIR                     63278
#define IDS_BARIUM                      63279
#define IDS_IODINE                      63280
#define IDS_GLUCAGON                    63281
#define IDS_BUSCOPAN                    63282
#define IDS_EXAMINATION_QUALITY         63283
#define IDS_CRADS_WEBLINK               63284
#define IDS_MEASUREMENT                 63285
#define IDS_STATUS_INDICATOR_LINKED     63286
#define IDS_STATUS_INDICATOR_UNLINKED   63287
#define IDS_PREFS_DEFAULTS_LAYOUT       63288
#define IDS_PREFS_DEFAULTS_LAYOUT_OPTIONS 63289
#define IDS_PREFS_DEFAULTS_MOUSE_COORDS 63290
#define IDS_PREFS_DEFAULTS_MOUSE_COORDS_OPTIONS 63291
#define IDS_PREFS_DEFAULTS_FLIGHT_SPEED 63292
#define IDS_PREFS_DEFAULTS_QUICK_ANNOTATION 63293
#define IDS_PREFS_DEFAULTS_SCROLLBAR_ORIENTATION 63294
#define IDS_PREFS_DEFAULTS_SCROLLBAR_ORIENTATION_OPTIONS 63295
#define IDS_PREFS_DEFAULTS_DISPLAY_EC_CAD 63296
#define IDS_PREFS_DEFAULTS_DISPLAY_CLEANSED 63297
#define IDS_PREFS_DEFAULTS_DISPLAY_CLEANSED_OPTIONS 63298
#define IDS_PREFS_DEFAULTS_2D_MEASUREMENT_PROFILE 63299
#define IDS_PREF_DEFAULTS_COLOR_SCHEME  63300
#define IDS_PREFS_DEFAULTS_COLOR_SCHEME 63300
#define IDS_PREFS_DEFAULTS_COLOR_SCHEME_OPTIONS 63301
#define IDS_PREFS_DEFAULTS_VOLUME_MEASURE 63302
#define IDS_PREFS_DEFAULTS_VOLUME_MEASURE_OPTIONS 63303
#define IDS_PREFS_DEFAULTS_LINK_DATASETS 63304
#define IDS_PREFS_DEFAULTS_DISPLAY_CENTERLINE 63305
#define IDS_PREFS_DEFAULTS_PSUEDO_COLOR 63306
#define IDS_PREFS_DEFAULTS_PSUEDO_COLOR_OPTIONS 63307
#define IDS_PREFS_DEFAULTS_RESET_BUTTON 63307
#define IDS_PREFS_DEFAULTS_YES_NO_OPTIONS 63308
#define IDS_PREFS_DEFAULTS_ON_OFF_OPTIONS 63309
#define IDS_PREFS_DEFAULTS_RESET_QUESTION 63310
#define IDS_PREFS_DEFAULTS_GENERAL_LABEL 63311
#define IDS_PREFS_DEFAULTS_DISPLAY_LABEL 63312
#define IDS_PREFS_DEFAULTS_APPLY_MESSAGE 63313
#define IDS_PREFS_DEFAULTS_WARNING      63313
#define IDS_PREFS_DEFAULTS_APPLY_NOW    63314
#define IDS_PREFS_DEFAULTS_FOV          63315
#define IDS_PROGRESS_DLG_LABEL          63316
#define IDS_REPORT_COMPLETED_STATUS     63317
#define IDS_PREFS_DEFAULTS_TOOLBAR_POSITION 63318
#define IDS_PREFS_DEFAULTS_TOOLBAR_POSITION_OPTIONS 63319
#define IDS_TRY_AGAIN                   64000
#define IDS_STRING1                     64001
#define IDS_EXIT_QUESTION               64001
#define IDS_COMPLETE_MESSAGE            64002
#define IDS_RENEWAL_FAILED              64003
#define IDS_USERNAME_MISSING            64004
#define IDS_PASSWORD_MISSING            64005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        388
#define _APS_NEXT_COMMAND_VALUE         32962
#define _APS_NEXT_CONTROL_VALUE         3279
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
